### ISSUE TITLE
The source code is not yet ready to be published open source

### ISSUE THREAD

**Issue by niomaster** [Inter-Actief/amelie#1]

**Comment by Tijnoz** [comment]
En nu dan?

**Comment by SebastiaandenBoer** [comment]
We should check license information for each of the libraries used

**Comment by windwarrior** [comment]
BSD, the license that most contributers agreed to, is GPL compatible and permissive in nature. I don't see much issue.

**Comment by Sophietje** [comment]
We (@AVeenstra @Kurocon @niomaster @SebastiaandenBoer  @Sophietje) have reached a consensus that the following things need to be fixed before going open source:
- [ ] Need to remove old Oauth library (assigned to @niomaster & @SebastiaandenBoer )
- [ ] GDPR, the privacy committee whether changes are needed regarding data storage (deadline: end of May)
- [ ] GDPR, we need to write  comments in the code that indicate privacy sensitivity (deadline: end of May)
- [ ] Translations: we need to finish translating the code base (see ticket #294) (deadline: end of June)
- [ ] Need to go through code to see whether there are no passwords, personal information, etc. hardcoded. (deadline: end of July)
- [ ] Generating dummy data (deadline: end of July) (assigned to @AVeenstra )

When these things are done we can make the code base open source.
After this we will need to add documentation (set up, installation, overview of module functionality).

If all of this has been finished, we would like to organize a WWW Hackathon so as to introduce Inter-Actief members to our code base and the possibility of

**Comment by Sophietje** [comment]
Ping: What's the state of the above mentioned points? Translations are finished right?

**Comment by AVeenstra** [comment]
Translations are indeed finished. So only #332 (Inter-Actief/amelie-private#371) and #340 are left. Feel free to work on them

**Comment by WKobes** [comment]
@Kurocon issue list completed. How shall we proceed?

**Comment by WKobes** [comment]
Possibly blocked by #523

**Comment by Kurocon** [comment]
As far as I'm concerned, everything is ready.

Procedure still needs to be discussed (i.e. how will we migrate open PRs on the private repo, how will we update www development environments on beta, pullmaster scripts, etc..)

**Comment by Kurocon** [comment]
Volgens mij is dit gelukt!
