### ISSUE TITLE
Accountnaam verplicht stellen bij het toevoegen van lid aan commissie

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#10]
Als een lid toegevoegd wordt aan een commissie, wordt dit lid netjes door Claudia in de juiste groep gezet. Dit kan echter alleen als de accountnaam ook ingevuld is. Het kan dus niet voorkomen dat het bestuur iemand in een commissie klikt zonder dat deze persoon een account krijgt (Claudia laat ik even buiten beschouwing, want dat heeft hier niet zoveel mee te maken). De accountnaam mag dus verplicht worden gesteld. Hier moet wel even over nagedacht worden. Het is zonde als je wel het formulier krijgt om mensen in commissies te klikken, maar dat je uiteindelijk niet op opslaan mag drukken. In dat geval moeten mensen het twee keer doen...

Een alternatief is om bij het openen van het formulier om mensen in te klikken, even een waarschuwing te geven dat de accountnaam nog niet ingevuld is.
---

Replying to lenthejm:

```
Een alternatief is om bij het openen van het formulier om mensen in te klikken, even een waarschuwing te geven dat de accountnaam nog niet ingevuld is.
```

Deze waarschuwing is er al, maar wordt blijkbaar soms genegeerd.
---

 Quick fix: maak een link in het formulier naar de profielpagina, dit is waar het ingevuld moet worden. Zodra dit een keer gedaan is zal dit duidelijk zijn.♥

**Comment by J3173** [comment]
Waarschuwing is er al. Verplicht stellen lijkt me niet handig, dit gaat stuk op het bewerken van de commissiegeschiedenis van mensen zonder accountnaam.

Zie ook #15.

**Comment by Kurocon** [comment]
Gefixt in https://github.com/Inter-Actief/amelie-private/pull/85
