### ISSUE TITLE
Make GMM a worthy component of the website

### ISSUE THREAD

**Issue by jochemschutte** [Inter-Actief/amelie#102]

**Comment by SebastiaandenBoer** [comment]
This would require the creation of the GMM module in the website, complete with administration system, etc.

At the moment, I'm going to pass on this issue as I am expecting to do an overhaul of the company corner in the near future. I might come back to this at one point, but if anyone feels like picking this issue up in the meantime, feel free to.

**Comment by WKobes** [comment]
Decided that this is not of added value right now.
