### ISSUE TITLE
SplitDurationWidget gaat stuk in nieuwe Django

### ISSUE THREAD

**Issue by niomaster** [Inter-Actief/amelie#104]

**Comment by Kurocon** [comment]
Lijkt nog te werken in 1.10, wat dacht je dat stuk zou gaan?

**Comment by Kurocon** [comment]
Bump? Lijkt nog steeds te werken op 1.11?

**Comment by niomaster** [comment]
I cannot reproduce the original error on staging, so we should probably close the ticket unless an issue arises.
