### ISSUE TITLE
Editing a transaction

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#11]
Als er handmatig transacties worden ingevoerd, wil hier nog wel eens foutje in sluipen. Slechts via /admin kunnen bedragen daarna nog gewijzigd worden. Beter kan dit ook via de website worden geregeld, zodat ook mijn lieve medebestuurders dit kunnen :) 

---

Waar ik aan zat te denken, is dat de transactie gefiatteerd wordt op het moment dat hij geëxporteerd wordt naar de (vernieuwde) incasso. Tot dat moment lijkt het mij veilig om veranderingen toe te staan.

**Comment by J3173** [comment]
De admin heeft inmiddels de genoemde logica: een transactie is te bewerken totdat er een incasso aangemaakt wordt. Dit zou ook in de normale website kunnen.
