### ISSUE TITLE
Custom forms lack non_field_errors

### ISSUE THREAD

**Issue by Tijnoz** [Inter-Actief/amelie#111]
Many custom forms (custom template forms) lack the non_field_errors variable. 
See https://docs.djangoproject.com/en/1.10/topics/forms/#rendering-fields-manually

**Comment by niomaster** [comment]
Well, let's get started then...

[ ] activiteiten
[ ] alv
[ ] api
[ ] bedrijven
[ ] bestanden
[ ] blame
[ ] claudia
[ ] dreamspark
[ ] iamailer
[ ] ianew
[ ] inbitweencheck
[ ] jelte
[ ] kalender
[ ] kamerdienst
[ ] leden
[ ] msdnaa
[ ] narrowcasting
[ ] nieuws
[ ] oauth2
[ ] oauth2lib
[ ] onderwijs
[ ] over
[ ] settings
[ ] statistics
[ ] streeplijst
[ ] tools
[ ] twitter
[ ] weekmail
