### ISSUE TITLE
Rename DreamSpark to Microsoft Imagine

### ISSUE THREAD

**Issue by J3173** [Inter-Actief/amelie#115]
Microsoft has renamed DreamSpark to Microsoft Imagine. This has to be changed in our website as well.

**Comment by AVeenstra** [comment]
Only the visual appearances of the word(s) Dreamspark( Premium) have been replaced as replacing other occurrences could have unexpected results. We could also add an url with the new name and redirect everything on /dreamspark to that one, but I am not sure if the login and logout is going to survive such a change.

**Comment by windwarrior** [comment]
For the urls I would do the following:

* Add an RedirectView for all url's starting with ^dreamspark/.
* Redefine the url for the dreamspark _app_ in the root urls.py to
^imagine/ or whatever is an appropriate name.
* Make the RedirectView just redirect to s/dreamspark/imagine/.

--Lennart

2016-09-16 17:42 GMT+02:00 AVeenstra <notifications@github.com>:

**Comment by AVeenstra** [comment]
> * Add an RedirectView for all url's starting with ^dreamspark/.
> * Redefine the url for the dreamspark _app_ in the root urls.py to ^imagine/ or whatever is an appropriate name. 
> * Make the RedirectView just redirect to s/dreamspark/imagine/.

is the same as:

> We could also add an url with the new name and redirect everything on /dreamspark to that one, but I am not sure if the login and logout is going to survive such a change.

Do you know if the login and logout is going to survive? I have no way of testing it. I already have the two lines to make it happen, but I don't like breaking things.

The two lines required:
`url(r'^dreamspark/(?P<path>.*)$', RedirectView.as_view(url='/microsoftimagine/%(path)s', permanent=True)),`
`url(r'^microsoftimagine/', include('amelie.dreamspark.urls')),`

**Comment by J3173** [comment]
Probably some settings need to be changed in the Microsoft Imagine store. The board should have access to it. ( @11gamer11 @niomaster )

**Comment by AVeenstra** [comment]
I changed the url, but we should not forget to change those settings if we push this to production
