### ISSUE TITLE
[easyfix] Button text on company page is incorrect

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#119]
The button text on the company blocks on the page https://www.inter-actief.utwente.nl/bedrijven/ show the text "{% trans 'Wijzig bedrijf' %}" literally. Somewhere, someone made an oopsie in the template.

**Comment by Kurocon** [comment]
Also on https://www.inter-actief.utwente.nl/bedrijven/oud/ but that might be the same template file

**Comment by Tijnoz** [comment]
Blijkbaar is dit stukgegaan door de reformat voor de indentation. I blame @J3173 ! :p
