### ISSUE TITLE
Forbid people to set @inter-actief.utwente.nl /@inter-actief.net addresses as their mail

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#120]
It would be nice to forbid people from setting e-mail addresses ending in the following on the website. They would cause a loop or at least unexplainable behaviour.

- @inter-actief.utwente.nl
- @ia.utwente.nl
- @inter-actief.net
- @inter-actief.nl

**Comment by J3173** [comment]
There are currently some use cases in which an @inter-actief.net address is used without problem:

- People of which the email address is invalid and no new email address is known are set to `unknownaddress@inter-actief.net`
- In the test environment the email addresses www@inter... and beheer@inter... are frequently used.

These use cases will break when implementing this issue. These have to be dealt with first.

**Comment by AVeenstra** [comment]
I can add separate cases for those addresses. The email addresses of the two committees can be accepted only if the DEBUG setting is set and the `unknownaddress` address can have its own exception to the rule.

Would that be sufficient?
