### ISSUE TITLE
Pictures in mailings not working

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#122]
Pictures do not show up in mails correctly. However, when viewing the mail online, everything works fine.

![capture](https://cloud.githubusercontent.com/assets/9413731/18627008/c67bbd96-7e58-11e6-9676-1eacbb6262b9.PNG)

Proof online mails work: 
https://www.inter-actief.utwente.nl/weekmail/archief/72/

**Comment by J3173** [comment]
My guess is the pictures don't work because the urls are not absolute, i.e. missing the domain name.
