### ISSUE TITLE
Ik wil graag de sectie "bedrijven" aanpassen door de linkjes te vervangen door een leuke tekst voor company corner. Prik mij voor tekst.

### ISSUE THREAD

**Issue by kimberlyh** [Inter-Actief/amelie#126]
[Please write your issue in English]

**Comment by Tijnoz** [comment]
"Please write your issue in English", I have really no clue what Prikking means!

**Comment by kimberlyh** [comment]
I would like to change the section "bedrijven" by replacing the links with a fun text for the company corner. Poke me for text.

**Comment by J3173** [comment]
Can you provide the text please? Then a new WWW member can make this happen.

**Comment by kimberlyh** [comment]
NL: 
"Bedrijven" renamen to "Company Corner"
In de Company Corner kun je informatie vinden over bedrijven en mogelijke afstudeerplekken of vacatures die zij bieden. <<insert link to company corner >>

EN:
"Companies" renamen to "Company Corner"
In the Company Corner you can find information about companies and possible graduation projects or job opportunities. << insert link to company corner >>
