### ISSUE TITLE
Hide very long activities from calendar export

### ISSUE THREAD

**Issue by stokworks** [Inter-Actief/amelie#131]
Study Tour MISC shows up as a very long block in my Google Calendar. Would it be possible to hide activities that take longer than (for example) 3 days? I think 3 days would be a good limit, as this takes into account that there are activities that take an entire weekend.

**Comment by Tijnoz** [comment]
Is helemaal hiden wel de oplossing? Mss de eerste en laatste dag erin zetten als Begin en End?

**Comment by stokworks** [comment]
Fair enough, vind ik wel teveel moeite om te coden :see_no_evil:

**Comment by stokworks** [comment]
Also: should our Pandora-activity be hidden? Maybe 5 days would be a better limit.

**Comment by Tijnoz** [comment]
Maybe you should write a custom ical middleware to hide the one event you wanted to filter out for yourself :P
