### ISSUE TITLE
og:image meta tag broken on activity pages

### ISSUE THREAD

**Issue by J3173** [Inter-Actief/amelie#132]
The `og:image` meta tag is broken on activity pages.

For example on https://www.inter-actief.utwente.nl/activiteiten/5340/:

```
<meta property="og:image" content="https://www.inter-actief.utwente.nl/activiteiten/5340/static/img/pdf/ialogo.png" />
```

This URL is invalid. This should be https://www.inter-actief.utwente.nl/static/img/pdf/ialogo.png

**Comment by Tijnoz** [comment]
This is my fault \o/ Will fix soon

**Comment by Marckvdv** [comment]
Fixed, see PR 93.
