### ISSUE TITLE
I cant read the text below the tv advertisements on https://www.inter-actief.utwente.nl/bedrijven/banners/ . The "expires on" and "active" texts overlap

### ISSUE THREAD

**Issue by kimberlyh** [Inter-Actief/amelie#135]
[Please write your issue in English]

**Comment by windwarrior** [comment]
This is still due to the transition to boostrap, so probably has to do with the widths of the elements.

**Comment by Sophietje** [comment]
We want to add a complete bootstrap build and take the parts necessary by importing 
- Nick

**Comment by nickschot** [comment]
Bootstrap is included by: https://github.com/Inter-Actief/amelie-private/pull/166

cc: @windwarrior
