### ISSUE TITLE
If somebody tries to log in with their s number and it is not recognized in the administration, you cannot go back to the homepage or any other page until you close the browser

### ISSUE THREAD

**Issue by kimberlyh** [Inter-Actief/amelie#136]
She logged in with a correct s number and password, but she made a typo in our database, so the s number was not recognized

**Comment by niomaster** [comment]
This is because a `User` is made without a `Persoon` for users that log in with their s-account, but are not a member: https://github.com/Inter-Actief/amelie-private/blob/master/amelie/tools/auth.py#L109

Can anyone tell me why we do this, instead of just denying the login?

**Comment by niomaster** [comment]
See here: https://github.com/Inter-Actief/amelie-private/pull/163

**Comment by J3173** [comment]
The reason not to deny the login is to be able to see the difference between wrong username/password and not correctly linked accounts.

My suggestion would be adding an logout button to https://github.com/Inter-Actief/amelie-private/blob/master/templates/profiel_onbekend.html .
