### ISSUE TITLE
Nationality needed to change my e-mail address?

### ISSUE THREAD

**Issue by MMeent** [Inter-Actief/amelie#139]
The nationality is a nullable & blankable field in the models, so why do I need to fill in my nationality to update my e-mail address?

Other questions about 'nationality':

1. How does it handle multiple nationalities?
2. Is no nationality really impossible/an invalid input? (could it happen?)
3. We have the setting 'language of preference', so what is 'nationality' actually used for?

**Comment by Sophietje** [comment]
I'm not entirely sure about your first question however you could see this as useful as it'll make users, who became a member before nationality was introduced, to fill in their nationality.

1, If you have multiple nationalities, you'll have to choose the one that you feel most associated with
2. I doubt whether you can have no nationality
3. Nationality is used to see how many international students there are. This is also used to determine how many active international members there are. If this number is very low, the board could choose to put some extra effort into making international students active.
