### ISSUE TITLE
The standard sentence about subscribing for an activity at the website

### ISSUE THREAD

**Issue by IrisRobin** [Inter-Actief/amelie#141]
The sentence  'For this activity there is no maximum number of participants. If you want to be there, you must enroll.' is not always true since for some activities subscription is not necessary (such as drinks). Maybe this can be changed by not showing this sentence when there is not a maximum number of participants who can subscribe for the activity.

**Comment by J3173** [comment]
> Maybe this can be changed by not showing this sentence when there is not a maximum number of participants who can subscribe for the activity.

I'm not sure this is always true, since there can be activities without a limit but enrolment is required.

**Comment by Sophietje** [comment]
Suggested solution is to add three different sentences. One for when there is no maximum number and no enrollment, one for when there is no maximum and you can enroll and one for when there is a maximum number.
