### ISSUE TITLE
Tables overflow (e.g. see old LAN enrollment)

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#142]
Could think about using responsive bootstrap tables.
(Can only be done after ticket #135)

**Comment by nickschot** [comment]
https://github.com/Inter-Actief/amelie-private/pull/166 makes it possible to use bootstrap tables.

**Comment by nickschot** [comment]
Necessary steps:

1. Uncomment tables in `amelie/ianew/static/less/bootstrap-custom.less`
2. Add `table table-responsive` and other necessary classes to the relevant tables
