### ISSUE TITLE
External members without a UT login cannot register new RFID cards

### ISSUE THREAD

**Issue by niomaster** [Inter-Actief/amelie#143]
External members that have no way of logging in cannot register new RFID cards. Can we get a form to add new ones at https://www.inter-actief.utwente.nl/streeplijst/persoon/1234 for the board?

**Comment by Sophietje** [comment]
Find out whether it is possible to add OAuth login on cookie corner pc without staying logged in otherwise add button that when a new card is 'bleeped' a board member can add this to a member.
