### ISSUE TITLE
API: Inconsistent naming

### ISSUE THREAD

**Issue by dexbleeker** [Inter-Actief/amelie#144]
The API-call _getCompanyStream_ returns the name of the company as **title**, where the _getCompanyDetailed_ uses **name**.
Please use just one (I prefer **name**) and deprecate the other.

Also; the API-call _get_activity_detail_ uses **pictures**, where  _get_latest_activity_with_pictures_ uses **photos**. Please use one (I prefer **pictures**) and deprecate the other.

**Comment by SebastiaandenBoer** [comment]
Inconsistency is also present in json attribute names such as isActive, beginDate and begin-date

**Comment by SebastiaandenBoer** [comment]
Inconsistency is also present in json attribute names such as isActive, beginDate and begin-date

**Comment by SebastiaandenBoer** [comment]
Inconsistency is also present in json attribute names such as isActive, beginDate and begin-date

**Comment by SebastiaandenBoer** [comment]
Inconsistency is also present in json attribute names such as isActive, beginDate and begin-date

**Comment by SebastiaandenBoer** [comment]
Inconsistency is also present in json attribute names such as isActive, beginDate and begin-date

**Comment by SebastiaandenBoer** [comment]
Inconsistency is also present in json attribute names such as isActive, beginDate and begin-date

**Comment by SebastiaandenBoer** [comment]
After deliberation we have now decided to use the [Google JSON Style Guide for property name formatting](https://google.github.io/styleguide/jsoncstyleguide.xml#Property_Name_Format). All affected properties will be deprecated, after which a new version of the API documentation will be released.

**Comment by SebastiaandenBoer** [comment]
This has been fixed in Inter-Actief/amelie-private#122
