### ISSUE TITLE
Edit a dogroup of a student

### ISSUE THREAD

**Issue by IrisRobin** [Inter-Actief/amelie#145]
If you want to edit/add a dogroup at 'student data' you can edit the dogroup, by using the 'tab' button, but it's not possible to push the 'ok' button since it is not on the page anymore.

**Comment by 11gamer11** [comment]
(Can only be done after ticket #135)

**Comment by SebastiaandenBoer** [comment]
This should now be fixed in Inter-Actief/amelie-private#250
