### ISSUE TITLE
The direct debit mailing should be sent in English to international students

### ISSUE THREAD

**Issue by dennis-cai** [Inter-Actief/amelie#146]
When sending a mailing for the direct debit (automatische incasso) of both the consumption list (streeplijst) and the contribution, I would like the mailing to be English when sent to international students, and Dutch when sent to Dutch students. Right now I only have the option to choose one of the languages for all students. The English text that should be sent is attached below.

[Direct debit.txt](https://github.com/Inter-Actief/amelie/files/570300/Direct.debit.txt)

**Comment by 11gamer11** [comment]
The hard coded template(s) should be a separate template which can be translated

**Comment by Kurocon** [comment]
See also Inter-Actief/amelie#66
