### ISSUE TITLE
Authenticated Apps do not seem to be listed properly

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#148]
The oauth_consumer_set property of the class Persoon does not seem to retrieve authenticated applications/ consumers as they are not properly displayed on the website. Tested authenticated applications, such as Cashflow symposium website and mobile apps, are not properly displayed.

**Comment by SebastiaandenBoer** [comment]
So is there currently a method to see which applications have access to your account from the website and if not, how easy is this to fix? Eventually, we want this to be able to be accessible from the mobile app too, if possible.

**Comment by windwarrior** [comment]
This is fixed now in Inter-Actief/amelie-private#97
