### ISSUE TITLE
[High priority] Addition of a reason code when adding a reversal of a debit entry

### ISSUE THREAD

**Issue by dennis-cai** [Inter-Actief/amelie#149]
When adding a reversal of a debit entry (terugboeking invoeren bij een incasso-instructie), I cannot select the reason code "DNOR" in the dropdown menu. I would like to have that added to the dropdown menu. It has high priority, since currently the money cannot be debited and the administration is not correct.

**Comment by 11gamer11** [comment]
We have to do some research in SEPA to see the consequences of DNOR.
