### ISSUE TITLE
API: signupAvailable is true also when no places are available anymore

### ISSUE THREAD

**Issue by dexbleeker** [Inter-Actief/amelie#157]
This is weird. When all places are filled, signup is **not** available.

**Comment by Sophietje** [comment]
signupAvailable is internally represented by whether an activity has a signup. You should use this field to determine whether you should render some sort of subscription buttons.

--Lennart

**Comment by dexbleeker** [comment]
That's what happens now. But like I said, it is weird. When all places are filled, I don't want (and shouldn't) to render the subscription buttons and stuff. The ideal way to determine if these buttons need to be rendered is via the signupAvailable-field. However, that field is now (incorrectly) reporting that signing up is still possible.

**Comment by SebastiaandenBoer** [comment]
The ideal way to determine if the signup button should be rendered is via the signupAvailable field, however, in best practice the amount of available places should be used to determine if the button should be activated or not.

In the situation you're proposing a user would find himself in a situation where it is impossible to determine whether the activity has a signup option or whether it is simply full. Instead, you could render the button, but have it disabled (perhaps with a message that signup is currently full).

**Comment by SebastiaandenBoer** [comment]
After further deliberation, it seems better to include the availability count in the signupAvailable property for the reason that the signupAvailable field currently measures more than the simply indication if signup is available for a specific activity, it also takes into consideration the signup timespan.
