### ISSUE TITLE
Beta doesnt do SSL, and Radius is broken on the new beta server

### ISSUE THREAD

**Issue by windwarrior** [Inter-Actief/amelie#158]
My account has quite some rights on various Inter-Actief servers, therefore I would prefer to not expose my login details to others. In the past I would use my RADIUS credentials on beta, since these cannot access physical machines.

Now that we migrated beta to another server, we cannot use RADIUS login anymore (I think this is IP locked), but lets face it, even using RADIUS login is a hack that is not supposed to protect me.

Therefore I would like to have some sort of SSL enabled solution for beta, good thing I found [django sslserver](https://github.com/teddziuba/django-sslserver), which should warp the development server into an SSL socket.

kthxpls

--windwarrior

**Comment by Kurocon** [comment]
I will look at this, seems like a good idea. I need to request an SSL certificate and change the amelie-personal scripts.

**Comment by Kurocon** [comment]
I've requested the IP addresses of the beta servers to be added to the RADIUS server whitelist of ICTS to make RADIUS login work again, and I have requested an SSL certificate for the HTTPS servers. I now need to wait for that to come in before I can configure the scripts.

**Comment by Kurocon** [comment]
The certificates are in, and I changed the {alexia,amelie,fiasco}-personal commands to use the SSL server. WWW-ers need to merge master into their branch to be able to use them. The RADIUS IP addresses aren't changed yet, so I'll leave the ticket open until that's fixed too.

**Comment by Kurocon** [comment]
ICTS has added ia-beta and ia-staging3 to their radius access list, so you should now be able to login to the development servers using your s-account.
