### ISSUE TITLE
API: Too long strings for dinner options

### ISSUE THREAD

**Issue by dexbleeker** [Inter-Actief/amelie#159]
This line defines the name of the dinner option (for an activity), returned by the API:
_"name": choice.gerecht.naam + ' - ' + choice.gerecht.restaurant.naam_
Personally, I think this is very ugly and should change.
I would like a different field (in addition to _id_, _name_, and _price_) **restaurant** (or something similar).

**Comment by SebastiaandenBoer** [comment]
This has now been fixed in Inter-Actief/amelie-private#115
