### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by dexbleeker** [Inter-Actief/amelie#165]
For an activity with dinner-options, the API returns something like this:
```json
{
  "result": {
    "x": "y", 
    "options": [{
      "question": "Eten",
      "choices": [{
        "name": "Taco kit classic - Taco Mundo",
        "x": "y",
      }]
    }]
}
```

The string "Eten" is not translated. Please make this translatable this also, so our (international) users get a question they can understand :)

**Comment by SebastiaandenBoer** [comment]
This seems to be an issue with there being no option to submit translated options to an activity. The front-end will need to be modified as well as the activity's option model. The API remains largely unaffected.

**Comment by Sophietje** [comment]
Committees are responsible for asking questions in English, therefore this will be a wontfix. Board 38 has been told about this issue.

**Comment by dexbleeker** [comment]
While that is true, my point was that it is not possible to have a different string for different languages in that field. It would be nice if both 'Food' and 'Eten' would be possible.

**Comment by Kurocon** [comment]
Discussed this in person with Dex, he now understands the policy of the board, it was just a bit of miscommunication.
