### ISSUE TITLE
Add markdown conversion to getnewsdetailed

### ISSUE THREAD

**Issue by 11gamer11** [Inter-Actief/amelie#166]

**Comment by windwarrior** [comment]
I am torn on this one, I understand the wish for these types of information, but I like to keep API responses concise.

My worst nightmare for the api would be that for any given possible application detail another key is added, what if people want textile/bbcode/whatever.  So, this inherently means that responses from the API are slightly opinionated in what you are expected to do with the response. See it like pythons "There should be one-- and preferably only one --obvious way to do it.".

Lets keep API responses concise, have a clarity of purpose and unduplicated.

**Comment by SebastiaandenBoer** [comment]
This could theoretically be solved by adding an extra parameter to the getNewsDetailed call, making the default value HTML, but allowing for markdown, thus not making responses longwinded.
This way, existing applications could continue to make use of HTML without any changes, though new applications COULD make use of markdown.

Within AppCie all three platforms agree on making use of markdown if available. Hence, this would not create the need for additional formats, keeping your worst nightmare limited to your dreams.

**Comment by Kurocon** [comment]
I agree with Sebastiaan, we can just add an extra parameter, something like `returnFormat` might be good?
