### ISSUE TITLE
Move wiki to github or wiki.ia

### ISSUE THREAD

**Issue by 11gamer11** [Inter-Actief/amelie#172]

**Comment by Kurocon** [comment]
A lot of the info on the trac wiki has become outdated or invalid with the passage of time. If we want to copy over the info, we have to be selective in what we need to copy over.

**Comment by Kurocon** [comment]
Started writing some new Getting Started guides at https://wiki.ia.utwente.nl/index.php/WWW:Main

**Comment by WKobes** [comment]
@Kurocon TRAC has been removed, right?
