### ISSUE TITLE
Video's on the homepage

### ISSUE THREAD

**Issue by J4sp3r** [Inter-Actief/amelie#175]
On the homepage, short versions of video's should play back besides the pictures. This depends on the new implementation of video objects of ticket #176.

**Comment by SebastiaandenBoer** [comment]
As the current photo slider relates photos to activities and videos do not, we either need to change the header of the slider section or we need to add a new section for most recent video. My preference goes to the latter

**Comment by SebastiaandenBoer** [comment]
After discussion, we have decided to make a small extra section block on the homepage underneath upcoming events, but above the company section to display a featured video, which would be indicated by the ```is_featured property``` in the ```YouTubeVideo``` model. If more exist, the most recent one is displayed.

**Comment by SebastiaandenBoer** [comment]
Due to company interest considerations, the implementation of this feature has been changed to the point where the video is now placed below the company section.

**Comment by windwarrior** [comment]
You can also consider adding a date to the featured-ness to prevent stale content on the front page. E.g. the promotional video for a symposium only occuring before said symposium

**Comment by SebastiaandenBoer** [comment]
Automatically the latest featured video is selected as it is the default sort, therefore, if you don't want to feature the anything else before the symposium, you won't toggle the featured button in a video edit form.
