### ISSUE TITLE
It is possible to delete contribution payments that are payed via direct debit

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#18]
~~Het is mogelijk contributie-betalingen van leden te verwijderen die via automatische incasso zijn betaald, terwijl dat eigenlijk via de streeplijst-incasso-frontend moet gebeuren.~~

It is possible to delete contribution payments that have been payed via direct debit, even though this should happen through the cookie-corner-direct-debit-frontend.

**Comment by AVeenstra** [comment]
Removing a contribution-payment should only be possible if no withdrawal has been attempted or if all withdrawals of the contribution payment have been "reversed" (gestorneerd).
