### ISSUE TITLE
How to deal with expired OAuth tokens on a person's profile?

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#182]
As of right now, expired tokens are apparently never removed from the user's profile, making the list longer than desired. Should there be a reasonable time period after which expired tokens are removed from the user's profile or deleted entirely?

![screenshot 6](https://cloud.githubusercontent.com/assets/7795655/21565860/0bdb095c-ce9d-11e6-8fa8-d0e7ebf94e4a.png)

**Comment by Kurocon** [comment]
I agree, we could check for and remove old tokens whenever a new one is issued. I think tokens older than a month can be safely removed.

**Comment by SebastiaandenBoer** [comment]
@Kurocon how about a revoke-all button? And I suggest removing tokens when expired, not when a new one is issued.

**Comment by Kurocon** [comment]
Of course I mean revoke old tokens if they have been expired for at least a month. A revoke-all button would also be nice for the privacy-paranoid amongst us.

**Comment by windwarrior** [comment]
django-oauth-toolkit does have a management command for clearing tokens that have been expired, they are just flagged now but they can be deleted I think.

**Comment by SebastiaandenBoer** [comment]
I'm just going to point out the obvious, but right now, the interface suggests we list OAuth2 **applications** even though we list OAuth2 tokens. There is no way to distinguish between different tokens as of right now.

I suggest we do one of three options:
1. Replace the tokens by proper applications and have users revoke applications rather than tokens.
2. Do option 1, but create a details page where users have control over the tokens as well
3. Add another column to the table providing users with the name or IP-address of the device last used with the token

**Comment by windwarrior** [comment]
Revoked tokens can be removed by a manage command, tokens already have an expire day, only thing that needs to happen (other then users removing their own) is cronjobbing that manage command.
