### ISSUE TITLE
Upload a picture to an event

### ISSUE THREAD

**Issue by kimberlyh** [Inter-Actief/amelie#188]
If you look at the description of an event now, it's just text (unless you fudge a picture in with markdown etc). For example: https://www.inter-actief.utwente.nl/activiteiten/5437/.  So it would be nice to be able to upload a picture which is then shown at the top of the page (a bit like a facebook event), or maybe at the side of the text description.

**Comment by Sophietje** [comment]
You can already add a picture to an event. See: https://www.inter-actief.utwente.nl/activiteiten/5221/. When you add an activity, there is a place just above the save button where you can upload an 'icon'. Is this functionality good enough for what you want to do/achieve?

**Comment by Sophietje** [comment]
So Kimberly wants to be able to add a picture in the event description. (See: https://www.inter-actief.utwente.nl/activiteiten/5479/). This is already possible however the pictures should be hosted somewhere. We want to fix this in such that IA will host all the pictures.

**Comment by Kurocon** [comment]
Then it's better to just allow an extra picture to be uploaded for events.

**Comment by WKobes** [comment]
We decided that this has too little value.
