### ISSUE TITLE
Remove nr of participants from API

### ISSUE THREAD

**Issue by 11gamer11** [Inter-Actief/amelie#192]
The API has to be edited that it is not possible to view how many people have signed up.

**Comment by Kurocon** [comment]
We would like to use the same policy as the one used for activities on the website: Make the amount of signups available only if you are logged in, and give an indication if you're not. The last part is already done by the `getActivityDetailed` method's `signupAvailable` property. The only thing we would need to change is make the `availability` and `signups` properties of that method only available if you are logged in.

**Comment by SebastiaandenBoer** [comment]
After discussion with the board, the `availability` property does not fall within the scope of this issue as it is only required to drop the amount of registrations, not the maximum amount of spots. Thus, the only property removed will be the `signups` property.
