### ISSUE TITLE
Change exports of CSV files to the .csv extension

### ISSUE THREAD

**Issue by dennisc19** [Inter-Actief/amelie#195]
Currently when exporting the table of enrollments, the site returns a comma-separated text file. It would be nice if the site would immediately return an Excel file, instead of having to manually import the comma-separated file.

Also, when pressing the "Printen" button on an activity page, the resulting printer-ready page has an ugly font that's not easy to read. I think that it would be a lot better if it could be updated to something like Verdana.

**Comment by Jottee** [comment]
Is there a way of testing this in the beta environment? Export only seems to load empty files

**Comment by Kurocon** [comment]
I just pushed a commit to master that fixes this problem. See Inter-Actief/amelie-private@25c2b3971eefcdaf899eeed6023e762dbc6f87a0 )

**Comment by Kurocon** [comment]
I was looking at some stale branches and encountered this issue.

In the code that generates this file, there is a comment stating:
```# Gebruik .txt. Excel 2007 forceert verkeerde tekencodering (niet UTF-8) bij .csv```

So unless that has been fixed in the newer Excel versions we might want to stick to using .txt
