### ISSUE TITLE
ics is not completely valid, VTIMEZONE needs to have STANDARD and DAYLIGHT sub-components

### ISSUE THREAD

**Issue by Magnificus36** [Inter-Actief/amelie#199]
The ics does no longer work in Outlook.com due to the fact that it is missing some information inside VTIMEZONE. When I manually add the missing information the ics is completely valid according to an online validator [1], and for me more importantly it then does work again Outlook.com. It was also this online validator [1] which pointed out that the current ics is invalid and is missing the STANDARD and DAYLIGHT sub-components.

More precisely, the ics currently contains:
```
BEGIN:VTIMEZONE
TZID:Europe/Amsterdam
END:VTIMEZONE
```
And this should be (something like):
```
BEGIN:VTIMEZONE
TZID:Europe/Amsterdam
X-LIC-LOCATION:Europe/Amsterdam
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
```
I copied this VTIMEZONE block from an ical generated by Google.
And, as already mentioned, with this replacement/addition the ics is valid and does work in the Outlook.com calendar.

1: http://severinghaus.org/projects/icv/?url=https%3A%2F%2Fwww.inter-actief.utwente.nl%2Factiviteiten%2Fkalender.ics

**Comment by niomaster** [comment]
Unfortunately this is not the canonical way in which daylight saving time is defined in python (see e.g. https://github.com/newvem/pytz/blob/master/pytz/zoneinfo/Europe/Amsterdam.py), and I'm  not sure whether I'm  in favor of hardcoding this.

**Comment by windwarrior** [comment]
How often do you intend to move Inter-_Actief_ to another timezone? :>

**Comment by niomaster** [comment]
Haha :), it's more that I'd rather not hardcode timezone data, i.e. if the government decides to discard daylight saving time, I'd prefer to "just update pytz", instead of having to update the definitions we made for ical (and what happens for past appointments? do all calendar applications work with the change? etc.)
