### ISSUE TITLE
Beveiliging van verjaardagen XMLRPC call

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#20]
In leden/xmlrpc.py staat op regel 30 een check of de user vanaf de UT komt (if not '130.89' in request.META.get('REMOTE_ADDR', ''):), dit exposed alle verjaardagen naar de hele campus, mijn suggestie is dan ook om dit via /api te gaan doen gezien daar authenticatie mogelijk is.

**Comment by J3173** [comment]
We gebruiken geen XMLRPC meer.
