### ISSUE TITLE
Activity descriptions have no markup in API call results

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#200]
When the apps get activity descriptions, and those descriptions contain markup or links, those are not returned and only plaintext is shown. This might also happen with other methods that return text that might contain markup or links on the website. (committees, complaints, etc..)

**Comment by SebastiaandenBoer** [comment]
I suggest that we use `render_markdown` and `strip_markdown` for all fields returned by the API that support markdown. One of these would be used depending on a passed parameter by clients.
