### ISSUE TITLE
[OAuth2] Add support for RFC7636

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#209]
Add support for the PKCE extension

https://tools.ietf.org/html/rfc7636#section-4.1

**Comment by windwarrior** [comment]
Is more something for [django-oauth-toolkit](https://github.com/evonove/django-oauth-toolkit) to implement, lets not as Inter-_Actief_ attempt to patch such a fundamental protocol extension on our (finally) industry standard library.
