### ISSUE TITLE
Foutmeldingen bij externe activiteiten worden niet netjes gerenderd

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#21]
Foutmeldingen bij externe activiteiten worden samen in een <p> element gestopt in plaats van dat er voor elke foutmelding een nieuwe <p> gegenereerd wordt. Verder worden foutmeldingen bij elke formset gererenderd in plaats van bij het veld waar de foutmelding betrekking op heeft

Kusjes, Lennart

**Comment by SebastiaandenBoer** [comment]
Error messages are rendered the same as with normal activities, do we still need to fix this then?

**Comment by SebastiaandenBoer** [comment]
Could not reproduce the issue after multiple tries with different people

**Comment by windwarrior** [comment]
Hai, the problem is that in both the normal and external activities, all errors are duplicated for each occurence of the `{% formset %}` tag. So if a page uses multiple formsets to create a nicer looking layout of a form (as the activity page and external activity page do), all unbound (errors not connected to a field) errors are rendered in each formset.

**Comment by Sophietje** [comment]
Maybe this has changed when the errors have been changed? First we add for all errors a little piece of text with a red cross icon next to it. Errors on most fields now have a sort of pop-up error. We tried to create errors in the external activity page, and no errors were rendered multiple times.

**Comment by SebastiaandenBoer** [comment]
It seems to be a problem after all after further investigation.

**Comment by SebastiaandenBoer** [comment]
@AVeenstra are you still planning on fixing this?

**Comment by Sophietje** [comment]
![img-20171030-wa0000](https://user-images.githubusercontent.com/5813135/32185594-e020199a-bd9f-11e7-9637-3d1ff8081db9.jpeg)

**Comment by SebastiaandenBoer** [comment]
Why is this not a screenshot?

**Comment by Sophietje** [comment]
Because you asked me to upload this photo

**Comment by Sophietje** [comment]
Duplicate of #210
