### ISSUE TITLE
Error displayed multiple times

### ISSUE THREAD

**Issue by 11gamer11** [Inter-Actief/amelie#210]
When you have the error 'Er is geen inschrijfstartdatum opgegeven.' in the activity form. It is displayed in 5 different places. Could be we other errors too.

**Comment by windwarrior** [comment]
This is an issue with how the form is compartimented in formsets, because eqch formset insists on rendering all errors that are not bound to a field.

Either bind errors to a field, or convince formsets to not render unbound errors

**Comment by WKobes** [comment]
This will be fixed in #174
