### ISSUE TITLE
Happy birthday, how old are you now? -I am 20 years and 12 months old.

### ISSUE THREAD

**Issue by Linths** [Inter-Actief/amelie#211]
![image](https://cloud.githubusercontent.com/assets/9081617/23588270/533a9550-01bb-11e7-985e-b8ba68fa305f.png)
I would suggest making it 25 years, or go all the way in months (the classic "I still see my child as a baby": "My son is 38 months old.").

**Comment by jackozi** [comment]
<img width="371" alt="screen shot 2017-06-12 at 15 39 15" src="https://user-images.githubusercontent.com/2853450/27036606-9d83b200-4f85-11e7-938f-5c54efcacb8d.png">

**Comment by Kurocon** [comment]
Deze pull request is al wel gemerged in master, maar nog niet doorgevoerd in productie. De bug is dus al gefixt en wordt zo snel mogelijk live gezet!
