### ISSUE TITLE
Enrollment options not bilingual

### ISSUE THREAD

**Issue by dennis-cai** [Inter-Actief/amelie#216]
The enrollment options can only be filled in in one language. There is no distinction as is normally the case on the website.

**Comment by SebastiaandenBoer** [comment]
Although this has been discussed before and we decided on using english-only options, personally I feel like it is better to have consistency throughout the website by having both dutch and english options.

**Comment by Kurocon** [comment]
We did discuss this before, see ticket #165. While it theoretically is possible to implement translatability on these fields, the fact that options can be dynamically added to events makes it a bit hard to make them 100% translatable. The last time (#165) the board told us their policy is just to tell committees to input them in English. If this really is an issue the board wants fixed then we can do it, but for now I'm closing this.
