### ISSUE TITLE
Stylesheet discussion

### ISSUE THREAD

**Issue by cwitteveen** [Inter-Actief/amelie#224]
When fixing #101 I had to change some css. I added some colors which where page-specific to another page. I don't think they should stay in the page specific css but where should i place it? i couldn't really find a stylesheet which was appropriate

**Comment by cwitteveen** [comment]
Also, the classes .activity-educational and .activity-external in /ianew/less/page-specific/frontpage.less assign colors to the <a> inside them, When i try to change this in such a way that the colors is assigned to the <a> with those classes, the colors get overridden with .current a. Is there a way which prevents this?

**Comment by Sophietje** [comment]
@nickschot Do you perhaps know what the best solution would be?
