### ISSUE TITLE
Committee details not aligned properly

### ISSUE THREAD

**Issue by dexbleeker** [Inter-Actief/amelie#226]
BS cols are used instead of table or rows (with cols). 

Example:
https://www.inter-actief.utwente.nl/commissies/260/international-business-course-commissie-2017/

**Comment by Kurocon** [comment]
Probably better to use a horizontal definition list here (`<dl class="dl-horizontal"><dt>thing</dt><dd>explanation</dd></dl>`) See http://getbootstrap.com/css/#type-lists
