### ISSUE TITLE
Make paginator on news pages consistent with other parts of the website

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#228]
The paginator at the bottom of [the news page](https://www.inter-actief.utwente.nl/nieuws/) is very ugly and not consistent with other pages, for instance at [the photo gallery](https://www.inter-actief.utwente.nl/activiteiten/fotos/)

**Comment by Kurocon** [comment]
Agreed.

**Comment by WKobes** [comment]
For some reason, this fix was undone in https://github.com/Inter-Actief/amelie-private/commit/e3982fa8b523cf6496c49d93a43d54a7c4b016be 

I fixed this now, but have a small change in comparison to the old fix: I do not think a paginator should be added on top, because older news messages are less relevant than for instance old pictures/video's. That is why I would only add a paginator to the bottom of the page.
