### ISSUE TITLE
Company corner url

### ISSUE THREAD

**Issue by kimberlyh** [Inter-Actief/amelie#234]
Allow for the url you have to enter (mandatory) in the company corner to show a different text.

For example:
In the text of the company corner you use markdown: [www.workingatasml.com/students](https://www.workingatasml.com/students?ppc=CAM-39), and it shows the first.

Now ASML wants to use the tracking url, but want to hide it, because it looks ugly. But I cannot do that in the url field so it looks like https://www.workingatasml.com/students?ppc=CAM-39.

**Comment by windwarrior** [comment]
you can just use markdown for this no?

```
[url you wanna see](url you wanna hide)
```

so in your case
```
[www.workingatasml.com/students](https://www.workingatasml.com/students?ppc=CAM-39)
```

**Comment by kimberlyh** [comment]
Yes I know that, but that doesn't seem to work in the url field when editing a company. (edit company > URL field below the field where you fill in the name of the company)

**Comment by niomaster** [comment]
This is about the text on the bottom: "For more information, see: {{company.url}}"

**Comment by windwarrior** [comment]
Right, but does that text need to be _customisable_, or does it need to say something like _the companies website_ which always hides the URL?

**Comment by kimberlyh** [comment]
I want the second option!

**Comment by windwarrior** [comment]
So basically `<a href={{company.url}}>Website of {{company.name}}</a>` with some magic trans stuff that the "website of " part gets properly translated.
