### ISSUE TITLE
Profielen wijzigen naar de nieuwe manier van Django

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#24]
We hebben nu een OneToOne? (denk ik) tussen Profiel en User, django echter heeft hier wat nieuwe ideeen over, check ​Django User Model documentatie even en update amelie naar de nieuwe situatie :).

**Comment by J3173** [comment]
Ik weet niet of updaten nodig is, aangezien een OneToOne relatie ook nog steeds een gesuggereerde oplossing is.

**Comment by Tijnoz** [comment]
Ik ben het eens met @J3173. Op deze manier schermen we ons ook het beste af van veranderingen die Django weer doet,
