### ISSUE TITLE
Horizontal alignment of category containers in "vertical view" of front-page

### ISSUE THREAD

**Issue by Linths** [Inter-Actief/amelie#240]
This happened when I was browsing the IA website in split-screen:
![image](https://cloud.githubusercontent.com/assets/9081617/25577529/ffcb88ce-2e66-11e7-9e5d-5a3f96b68d41.png)
Please note that none of the three pictured blocks seem to be aligned with one another.

**Comment by Sophietje** [comment]
This ticket is a duplicate of ticket #230
