### ISSUE TITLE
Foto's zichtbaar die afgeschermd zouden moeten zijn

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#25]
[Mail gestuurd aan de WWW] Beste WWW,

Omdat ik het ticketsysteem weer eens kwijt ben stuur ik jullie maar weer eens een mailtje.

Het viel me op dat de foto's van afgeschermde fotoalbum's onafgeschermd zijn. Als jullie niet helemaal begrijpen wat ik bedoel: Foto's van de OWIHFOEMTZ zijn gewoon zichtbaar als je niet bent ingelogd. Zie bijvoorbeeld als je niet ingelogd bent: ​https://www.inter-actief.utwente.nl/site_media/data/image/origineel/2013/10/10/OWIHFOEMTZ_CasEbbers_095.jpg

Zoals te zien is deze URL ook niet al te moeilijk te achterhalen. Misschien kunnen jullie hier iets aan doen door permissies goed in te stellen.

**Comment by J3173** [comment]
Nog steeds stuk maar op nieuwe URL: https://media.ia.utwente.nl/amelie/data/image/origineel/2013/10/10/OWIHFOEMTZ_CasEbbers_095.jpg

**Comment by Kurocon** [comment]
Is eigenlijk een ding wat Systeembeheer op de een of andere manier op moet lossen, ik weet niet of we daar binnen de site iets mee kunnen

**Comment by windwarrior** [comment]
Dat is niet helemaal waar @Kurocon, bijvoorbeeld pasfotos worden door django geroute en kunnen alleen benaderd worden door ingelogde en toegestane gebruikers.

Wat hier in principe misgaat is dat "niet publieke fotos" in een publiek media mapje staan dat apache gewoon netjes serveert.

Of het makkelijk op te lossen is durf ik wel een beetje te betwijfelen, je zou sommige (OWIFOEMTZ) fotos door django moeten routen, en andere liever niet. Klinkt asl veel werk.
