### ISSUE TITLE
Poster template InDesign

### ISSUE THREAD

**Issue by dennis-cai** [Inter-Actief/amelie#251]
Currently there only is an Adobe Illustrator poster template on the corporate design page. An InDesign template has been created as well, could you add it to the page? Since Waffle.io has no option to attach documents to tickets I have sent it to the WWW by mail.

**Comment by Kurocon** [comment]
This needs to be added to the Huisstijl-website ( [Inter-Actief/fancie-huisstijldocument](https://github.com/Inter-Actief/fancie-huisstijldocument) ), not Amelie.
