### ISSUE TITLE
Batch aliases

### ISSUE THREAD

**Issue by dennis-cai** [Inter-Actief/amelie#254]

**Comment by dennis-cai** [comment]
Currently you have to add members one by one to an email alias. This requires 3 steps per member that has to be added, and if you have many people to add this can be quite cumbersome. It would be nice if a batch option could be added which would make it easier to add a lot of people to an alias.

**Comment by Kurocon** [comment]
We do not want to do this, because this incites the creation of 'useless' aliases for 'useless' stuff. There are not many times when you would need a batch edit.
