### ISSUE TITLE
WeekMail: Include links back to the site for Activities/News/...

### ISSUE THREAD

**Issue by dennis-cai** [Inter-Actief/amelie#256]
Currently the weekmail is static, there are no links that takes you to the IA website so you can easily enroll.

**Comment by windwarrior** [comment]
Do you want:

1. Links from the WeekMail to the various activities, so clicking on a heading of an activity in the weekmail leads you to the website? Or have enrollment links for activities with enrollment? [Easy]
2. Links in the body of texts to various sources. We have those, you can have a link in an activities description, but if these links are relative they might break. Fixing that is either [Easy] or [Very Hard] depending on whether setting a [`<base>` tag](https://developer.mozilla.org/en/docs/Web/HTML/Element/base) is supported by the horror that is E-mail HTML.

**Comment by dennis-cai** [comment]
I want option 1,  clicking on a heading of an activity in the weekmail leads you to the website.
