### ISSUE TITLE
Kijken naar djangosaml2 voor SAML authenticatie

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#257]
Om gebruik te kunnen maken van de fancy SAML login van de UT moeten we een service provider worden. Djangosaml2 lijkt redelijk up-to-date, en goed te integreren. Meer informatie vanuit LISA komt waarschijnlijk nog, maar wel leuk om alvast te beginnen.

https://github.com/knaperek/djangosaml2

**Comment by Kurocon** [comment]
PR staat open, het is nu een mail sturen naar LISA dat onze implementatie klaar is zodat zij onze productieserver in hun productieserver kunnen toevoegen. Dat ga ik binnenkort fixen.

**Comment by WKobes** [comment]
Volgens onze administratie wordt er door jullie vereniging gebruik gemaakt van applicatieservers die authentiseren via Radius.  Afgesproken is dat we op 1 december 2019 deze radius-authenticatie gaan stoppen. Om de continuïteit te waarborgen moeten systemen volgens aansluitbeleid aangesloten worden.  Dit betekend voor jullie dat er geauthentiseerd moet worden met SAML.

 

De vraag is met wie kan ik contactnemen om deze migratie af te stemmen?

LISA heeft kennis van authenticatie via SAML, hebben jullie behoefte aan ondersteuning?

**Comment by Kurocon** [comment]
Tot zover 'binnenkort' :P

Ik zal er ergens deze week wel even achteraan gaan
