### ISSUE TITLE
Streeplijsttransacties datumrange

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#26]
Bij het genereren van de streeplijststatistieken moet je een van/tot datum aangeven. Deze range staat echter ingesteld op 2013-mm-dd tot 2014-mm-dd. Niemand heeft 2013 nodig, mijn voorstel is 2014-mm-1-01 tot 2014-mm-01 waarbij mm de huidige maand is.

**Comment by J3173** [comment]
Is inmiddels gefikst.
