### ISSUE TITLE
News block on frontpage shows button 'bericht toevoegen'

### ISSUE THREAD

**Issue by stephengeerlings** [Inter-Actief/amelie#260]
I should not have those permissions. After clicking on it I get an internal server error. You've probably recieved the email :)

![nieuws toevoegen](https://user-images.githubusercontent.com/2988577/27476674-f2e3741a-5809-11e7-9c26-aaccd4ae0f38.png)

**Comment by windwarrior** [comment]
Everyone who is active can post news items, you are part of the "tappersgilde" and therefore still active. What yields the internal server error is unknown to me, but the details are in sentry
