### ISSUE TITLE
Dutch in Membership renewal mail

### ISSUE THREAD

**Issue by Jottee** [Inter-Actief/amelie#264]
At the English version of the membership renewal mail, all the Preferences are still stated in Dutch

**Comment by Kurocon** [comment]
Should be easy, the `Voorkeur`-model already has fields for dutch and english, so it's probably just a templating issue.

**Comment by Kurocon** [comment]
This was fixed back in 2018 already: Inter-Actief/amelie-private@9ac66ba9835435907372a8891ba6b5d43866e010
