### ISSUE TITLE
Missing updated preferences in Altered Profile mail

### ISSUE THREAD

**Issue by Jottee** [Inter-Actief/amelie#265]
When a member changes their profile data a mail containing the changes is sent to secretaris@inter-actief.net. This also contains their changed preferences with the old ones before the --> and the updated ones after the arrow. The list of updated preferences is however incomplete.
For example: 'mail_birthday' is stated before the arrow but not afterwards, while this option is still active.

**Comment by Kurocon** [comment]
Probably an error in the mail generation. The form responsible for the e-mails is in  `amelie.leden.forms`, the code that sends the e-mail is located in the save function of the `ControleerForm`.
