### ISSUE TITLE
Terugknop van browser van streeplijst geeft sessie van vorige gebruiker

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#27]
Als je de terugknop van de browser van de streeplijst gebruikt kun je in de sessie van een vorige gebruiker komen en cookies kopen onder zijn naam. Blijkbaar wordt de sessie niet goed gesloten of zit er geen unieke token in het inlogsysteem.

**Comment by niomaster** [comment]
Ik kan dit niet reproduceren, de items komen niet op de streeplijst en hij gaat ook niet langs het successcherm? Als men het graag wil zou je in plaats van naar de standaard info-pagina kunnen redirecten naar een pagina die zegt dat je niet mag strepen, maar er wordt dus in ieder geval niet daadwerkelijk gestreept
