### ISSUE TITLE
Some e-mail validations are missing

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#270]
Last year we added some extra verification on e-mail addresses of members so they don't accidentally enter their IA-email and create a mail loop. This was changed in the profile form of members, but not in the other forms where e-mail addresses can be added to the system. We need to check those forms and add the verification there as well. The forms I remember are listed below, but there might be more:
- Member edit form for boards (/leden/<lid>/wijzig)
- Claudia edit forms (adding e-mails to mappings)

We previously thought this would not be necessary, but the board has already made 2 e-mail loops this year because they tried to fix their e-mail forwards. These are sometimes not caught when verifying the mapping for some reason, resulting in them staying active in WESP but removed in Amelie.

**Comment by WKobes** [comment]
@Kurocon please check for relevance since GSuite

**Comment by Kurocon** [comment]
Underlying issue (able to enter invalid mails) still present.
Added issue: You should only be able to enter IA mails in the committee email fields, and email fields for groups in Claudia. The board messed this up yesterday and entered a gmail address for a committee, breaking our gsuite
