### ISSUE TITLE
Can't enroll for activities in the app

### ISSUE THREAD

**Issue by cwitteveen** [Inter-Actief/amelie#272]
When trying to enroll for an activity, you get an message saying "Enrollment failed". This happens in both the android and the windows app.

**Comment by SebastiaandenBoer** [comment]
Correct, I have noticed this issue and tested it against the current codebase on master, however no error is thrown or passed to the client. In fact, I get a nice and clean response:
```
{
    "id": "Windows",
    "jsonrpc": "2.0",
    "result": true
}
```
for the following call:
```
{
  "jsonrpc": "2.0",
  "id": "Windows",
  "method": "activitySignup",
  "params": [5572, "10.50", [{
  	"id": 555,
  	"value": true
  },{
  	"id": 556,
  	"value": 2529
  }]]
}
```
given of course that the authentication headers are properly set and use a valid token.

**Comment by SebastiaandenBoer** [comment]
This seems to be an issue in the mobile apps and is not related to any code or deployment issues as it has been tested on both production and develop.
