### ISSUE TITLE
Translation pages for members

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#278]
Hello, 😀. Could you please translate every page of inter-actief? The part for members is not English. Thanks (was mailed to WWW)

**Comment by windwarrior** [comment]
Do you know which page is referred to, because I could not find an untranslated page :(.

**Comment by SebastiaandenBoer** [comment]
-[ ] assignments by the UT
-[ ] MSDNAA

**Comment by Jottee** [comment]
The assignments by the UT page will be translated by a board member, could someone however change the 'assignment by the UT' to 'assignments by the UT' in the dropdown options?

**Comment by WKobes** [comment]
Since MSDNAA is removed from the front-end and the assignment page is translated, this issue is solved.
