### ISSUE TITLE
Image upload staat html pagina's toe

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#28]
De image upload van activiteiten (en mogelijk van de flitcie?) staat gebruikers toe html pagina's te uploaden. Deze files worden geaccepteerd als ze maar beginnen met valide image headers. Als de extensie echter .html is wordt de file door de browser als html geparsed en is xss dus mogelijk. 

---

Wat django erover te zeggen heeft:

​https://docs.djangoproject.com/en/dev/topics/security/#user-uploaded-content

**Comment by J3173** [comment]
Misschien tegenwoordig minder een probleem aangezien geüploade files tegenwoordig vanaf een ander domein, namelijk https://media.ia.utwente.nl, komen.

**Comment by Tijnoz** [comment]
Wel een probleem als je op een andere manier dat bestand aan je geserved kan krijgen over het normale domein

**Comment by windwarrior** [comment]
@Martijn, how? Any media file should be included using the [% media %] tag, which by definition should use the correct media url.

Is it still an security issue when it is totally impossible to serve these files from the non-media domain?

**Comment by SebastiaandenBoer** [comment]
So @windwarrior, from your remark I take it that it is not an issue anymore? If so, can we close this ticket?

**Comment by windwarrior** [comment]
Yeah I think so, but @Tijnoz still hasn't responded.

**Comment by Kurocon** [comment]
Not an issue any more because of media.ia.utwente.nl
