### ISSUE TITLE
More details in the automatic debt collection mail

### ISSUE THREAD

**Issue by Linths** [Inter-Actief/amelie#280]
Including literally all your transactions in this mail would generate immensely long mails. However, we could show the sum of your transactions per category: cookie corner, drinks and activities. That way, you have already got a bit more insight of your spendings.

I have always found clicking the link another step (especially because I still find the transaction overview not that intuitive or easy to use, but that might just be my personal experience).

**Comment by Sophietje** [comment]
For the one who will fix this, you can consider the following options:
1. Put a link to the specific overview of the direct debit
2. Put an overview in the mail (this is likely a lot more work)
3. Do both

**Comment by AVeenstra** [comment]
url should be something like https://www.inter-actief.utwente.nl/streeplijst/incassoinstructie/{{{{instructie.pk}}}}/ and can be found in streeplijst/views.py
