### ISSUE TITLE
Change "bedrijfsactiviteiten" to "externe activiteiten" in /bedrijven/activiteiten/

### ISSUE THREAD

**Issue by Floormidabel** [Inter-Actief/amelie#281]
Right now the homepage says "externe activiteiten" or "external activities". When clicking it you go to a page called "bedrijfsactiviteiten" or "company activities" this should be external just like on the homepage because the activities there are not all company related.

**Comment by windwarrior** [comment]
How about the URL, its now `/bedrijven/activiteiten`, but changing it would mean that permalinks break...

**Comment by Sophietje** [comment]
We could add redirects for the 'old' permalinks in that case.?

**Comment by SebastiaandenBoer** [comment]
But then the activities would have to be a sub-item of activities and not companies anymore. Not sure if companies would want that. Perhaps a Company Activity could extend an External Activity?

**Comment by Floormidabel** [comment]
We define company activities as "external activities" when selling them, we also call it our "external activities calendar" so it is fine if all of this is one the exact same page.
