### ISSUE TITLE
Study names and abbreviations are not up to date

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#285]
Since a lot of studies became international, the names and abbreviations changed.

For instance, B-TI changed to B-CS

B-CS was Communication Science before, but that study is now B-COM.

This is only one example. The list should be updated accordingly

**Comment by windwarrior** [comment]
I am going to go ahead and tag @J3173 in this one, I believe he managed to gain a list of bachelor programs at some point a few years ago (I think approx 2013/2014) and also remember that it was a mess to get right.

**Comment by SebastiaandenBoer** [comment]
Well, there is actually a list on the University of Twente website where it lists all studies (bachelors and masters) per faculty: https://www.utwente.nl/en/bms/education/#information-for-prospective-students (BMS example)

**Comment by windwarrior** [comment]
Those are "marketing names" tho, I remember from the discussions of 2013/2014 that "Business and IT" was - for the systems of the UT - still called "Bedrijfs informatie technologie". I think Jelte spent condirable time to find the "internal" name.

**Comment by J3173** [comment]
You can find the official study names in the select boxes on https://osiris.utwente.nl/student/OnderwijsCatalogusZoekCursus.do
The abbreviations can be found in the source code of the select box and you can change the OSIRIS language to get the translations.

You can also check with the iDB committee of the Kick-In because they maintain a similar list.

**Comment by SebastiaandenBoer** [comment]
7) Faculty names should also be updated where applicable
8) Make sure that new members can no longer select older study names
8.1) Alter/ update list with new study names
10) Ongoing studies can have their names updated accordingly

**Comment by windwarrior** [comment]
2) Make sure that new members can no longer select older study names

This is not neccesairily true, prior to i18n, a student would have studied "Technische Informatica" while it probably changed to "Computer Science" after i18n. However, someone who started TI prior to i18n is still studying TI.

**Comment by SebastiaandenBoer** [comment]
Fair enough, see my revised list

**Comment by SebastiaandenBoer** [comment]
This can be changed in the admin panel of Django as they are model objects. There does not seem to be a code change required.

**Comment by Kurocon** [comment]
Fixed
