### ISSUE TITLE
Filter on no do group

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#287]
In https://www.inter-actief.utwente.nl/leden/ it is possible to filter on specific dogroup(s). However, it is not possible to filter on people without a do group.

We could use this to check if all members are added to their corresponding do group, or for instance invite all people that did not attend the Kick-In for a specific do group lunch.

Thanks!

**Comment by SebastiaandenBoer** [comment]
We can add an advanced search option (boolean) "is not part of a dogroup" that will filter people with a do group and only display members without a dogroup.
