### ISSUE TITLE
External option for photographer

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#288]
In https://www.inter-actief.utwente.nl/activiteiten/fotos/upload/, you can currently select all active members as photographer. However, sometimes we get pictures provided from other parties. For this, we would like to be able to select an 'external' option as photographer.

Use cases are for instance the bachelor graduation and photos made by UT employees, U-Today etc.

**Comment by SebastiaandenBoer** [comment]
This can easily be resolved by adding a text option for the photographer when creating a picture or album (see company/ external events). The photographer name can consequently be requested from the front-end using a function property that checks whether the photographer is a text field or a person.
