### ISSUE TITLE
Revamp company corner

### ISSUE THREAD

**Issue by Floormidabel** [Inter-Actief/amelie#289]
At this moment the company corner is a list in alphabetical order, a company indicated that they are interested but do not want it because their company name begins with a T. Could you make it so that every time you visit the company corner the entire page is randomized?

**Comment by Kurocon** [comment]
Of course this is possible, but it is also pretty user-unfriendly...

Are there any alternatives that they might be OK with too? We could maybe sort the companies by the date their contract was last prolonged or something like that? Maybe a redesign of the page so more companies are shown on a single page, with a "landing page" with boxes before you see any information on a company?

Any other www members / board members have an idea?

**Comment by Floormidabel** [comment]
Well my follow-up request would be a total rework of the page with tiles and everything, but I thought this could be a quick fix for now. On the other hand you are right about user friendliness, which is probably a lot more important than fairness :P

**Comment by SebastiaandenBoer** [comment]
I would honestly opt for the redesign as it would also provide a good opportunity to include promotion videos into the page as currently being worked on for the TV. I'd even go as far as to say that I'd be excited to design and implement a new company corner layout :)

**Comment by SebastiaandenBoer** [comment]
I will wait with starting this until the translation branch for companies has been merged back into master.
