### ISSUE TITLE
Veilige noframe / anti-xss headers ontbreken

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#29]
Noframe headers beschermen websites tegen framing, dit beschermt de website tegen privacy lekken en redress attacks.

Anti-xss headers stellen in hoe reflected-xss filters van browsers om moeten gaan met xss. De standaardmodus is niet geweldig, ik raad aan ofwel niets te blokkeren ofwel volledig te blokkeren wanneer xss wordt waargenomen. ("X-XSS-Protection: 0;" of "X-XSS-Protection: 1; mode=block")

---

 We kunnen hier even naar kijken: ​http://django-secure.readthedocs.org/en/latest/middleware.html

**Comment by AVeenstra** [comment]
x-xss-protection should be done by apache
