### ISSUE TITLE
API: Twitter should be removed from API

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#290]
Twitter should live in the Narrowcasting module and not in the News module as it is primarily used for advertisements instead of news updates. Currently, news is buried under Twitter messages as there is little news in general.

**Comment by SebastiaandenBoer** [comment]
After some researching, it seems as if the replication of the Twitter API (which is basically what we're doing) is not allowed by the developer terms and conditions of Twitter.

Therefore, I suggest we remove Twitter from the API all together and direct developers using the Inter-/Actief/ API to use the Twitter API instead for retrieving Inter-/Actief/ messages.

**Comment by SebastiaandenBoer** [comment]
To clarify, this would still allow the board to send messages to Twitter using the web interface.

**Comment by Kurocon** [comment]
Seems like a good idea to remove it then, as long as things like news messages and stuff still keep getting pushed to Twitter.

For the apps side of things, it might be better to split up the news section into news from the site and Twitter messages, this would become easier if the Twitter API part is removed too

**Comment by SebastiaandenBoer** [comment]
Okay, I'm going to remove Twitter from the IA API in that case.

> "For the apps side of things, it might be better to split up the news section into news from the site and Twitter messages, this would become easier if the Twitter API part is removed too"
This has to be taken on by individual apps, such as the ones created by the AppCie if the board sees this as important. This will also provide more freedom for app developers wanting to make use of the IA API.
