### ISSUE TITLE
Option to change your profile picture

### ISSUE THREAD

**Issue by FrankvanMourik** [Inter-Actief/amelie#292]

**Comment by FrankvanMourik** [comment]
One's profile picture on the website is a random photo that is taken on the first day of the faculty kick-in. Some people might want to change that picture since they do not like it.

**Comment by SebastiaandenBoer** [comment]
It was decided a long time ago that this would not be changed as it retains a historic value. In the past, these pictures were taken during the kickin as well and used in yearbooks afterwards.

I am not aware of the current situation, though as this was a previously discussed issue (not on GitHub though), I'm leaning towards seeing this as a non-issue.

**Comment by windwarrior** [comment]
I furthermore think the profile picture is only used in `/leden` and your
personal profile page. Basically no-one but the board and yourself get to
see that pic.

2017-11-09 14:19 GMT+01:00 Sebastiaan den Boer <notifications@github.com>:

**Comment by SebastiaandenBoer** [comment]
I guess it's a problem for some when they look at their profile picture and get reminded of their hungover face =P

**Comment by Sophietje** [comment]
Kevin and I would only think about changing this when we actually use the photo for something else for example when one could see a photo on someone's birthday. For now the photo is only visible for the board and the user him-/herself.

**Comment by SebastiaandenBoer** [comment]
Any person is able to request the takedown of specific personal data as per Dutch law. Therefore, if a person wants their photo removed, we are required to do so. However, which pictures are used is up to the association.

Therefore, I propose that we add an option to the profile page that allows the user to hide their profile picture from other uses on the IA website (the API should also be included as it is externally available).

This would allow people to hide their profile picture for non-essential purposes if they are not satisfied with it. However, this solution also means that profile pictures would remain available wherever they are currently used or where they are considered essential.

**Comment by Sophietje** [comment]
Conclusion: Add a field or visibility toggle to the Person model to let users indicate whether they want their profile picture hidden

**Comment by SebastiaandenBoer** [comment]
Coming back to this issue, I now realize that even with the profile picture being used elsewhere on the website, it would only still be visible to the board and to the user him-/herself. As pictures can be removed on request of the user, there does not seem to be a need to have a toggle as it would only introduce additional complexity.

**Comment by SebastiaandenBoer** [comment]
After some discussion, we have settled on displaying some text indicating that a change or deletion can be requested with the board. Reasons for this include that we do not want to make it too easy to permanently delete your profile picture without being able to change it yourself (the latter was decided on previously).
