### ISSUE TITLE
Translate codebase

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#294]
The codebase is still largely in Dutch which is a problem especially now that we have non-Dutch speaking members in the committee. Thus we should translate it asap.

**Comment by Sophietje** [comment]
Need to find out what the proper (and most fail-safe) way is to rename Django modules. Simply making migrations (when the module directory has been renamed) results in issues.

**Comment by SebastiaandenBoer** [comment]
In the amelie directory:

- [ ] activiteiten
- [ ] alv
- [ ] api
- [ ] bedrijven
- [ ] bestanden
- [ ] blame
- [ ] claudia
- [ ] dreamspark
- [ ] iamailer
- [ ] ianew
- [ ] inbitweencheck
- [ ] jelte
- [ ] kalender
- [ ] kamerdienst
- [ ] leden
- [ ] msdnaa
- [ ] narrowcasting
- [ ] nieuws
- [ ] oauth2
- [ ] oauth2lib
- [ ] onderwijs
- [ ] over
- [ ] settings
- [ ] statistics
- [ ] streeplijst
- [ ] tools
- [ ] twitter
- [ ] videos
- [ ] weekmail

Files in amelie directory:
- [ ] forms.py
- [ ] test_translation.py
- [ ] test_urls.py
- [ ] urls.py
- [ ] views.py

Files in the scripts directory:
- [ ] compile_css.sh

Other top-level project directories of which their files need translating:
- [ ] templates
- [ ] locale (?)

Other files that need translating that were not included in any of the above:
- [ ] pullmaster.sh

**Comment by SebastiaandenBoer** [comment]
All translation branches should branch from `ticket294`. Only after all branches have been merged back into `ticket294` we can merge this branch into `master`.
