### ISSUE TITLE
restaurants two step selection

### ISSUE THREAD

**Issue by Floormidabel** [Inter-Actief/amelie#296]
At this moment the options for food are one step, while thuisbezorgd has two steps very often. 
It would be really useful to support this in the food options. For example wok2go has bami nasi or rijst. Now I added everything from wok2go three times, once with every option, but it would be much more concise if I could add the bami nasi or rijst options after the main option is chosen, so that the list is shorter.

**Comment by SebastiaandenBoer** [comment]
I agree with the statement made here - I actually quite like the idea a lot -, but I'd like to mention that signups through the API and therefore the mobile apps are likely to break if any changes are made to this specific process.

**Comment by SebastiaandenBoer** [comment]
Sophie and I have discussed this and we believe that although it would be nice to include a feature like this, it is likely to break the website in too many places. Also, there does not seem to be a straight-forward way of implementing this feature. Therefore, we currently do not plan on implementing the requested changes.
