### ISSUE TITLE
SMS/push notifications not working correctly 

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#297]
Sending a SMS currently fails for all recipients. When logging in to our SMS service provider, there is still credit, but no requests get accepted. Perhaps look into the API of the site?

**Comment by SebastiaandenBoer** [comment]
This issue seems to extend to the psuh notifications, not just SMS. This needs to be resolved as well.

**Comment by SebastiaandenBoer** [comment]
I suggest that we use SMS messages only in case a person has no registered push (FCM) device. This would make SMS a backup option and prefer push over SMS. This can save money and improve user experience, as messages are no longer sent twice.

**Comment by SebastiaandenBoer** [comment]
Since #298 has been closed. I'm closing this ticket.
