### ISSUE TITLE
Claudia omzetten naar nieuwe stijl django

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#30]
Meer brainstorm in Boston,

Ik en Jelte hebben even gebrainstormd in het koude Boston. Een huidig probleem van de WWW is dat er op allerlei plekken allerlei methodes van django gebruikt worden, om consistentie te krijgen in de codebase moet er een voorbeeld bestaan van hoe huidige django code eruit moet zien. Jelte merkte op dat Claudia weinig magie bevat in zijn CRUD views dus dat we deze het makkelijkst onder handen kunnen nemen dus dat is ons idee dan ook maar :).

**Comment by Kurocon** [comment]
Ben ik al druk mee bezig!

**Comment by Sophietje** [comment]
Goed bezig!
