### ISSUE TITLE
Privacy policy is not translated

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#304]
The privacy policy on the website is not translated.

**Comment by SebastiaandenBoer** [comment]
Due to the GDPR going into effect later this May and the possible legal effects if this issue is not resolved before that time, I believe this issue should be marked as priority. Especially since it is an easy-fix.

**Comment by SebastiaandenBoer** [comment]
We're going to have a talk among each other about the privacy policy and the effect of the GDPR. Although this remains a priority, it seems reasonable to wait for this talk to have taken place before translating the privacy policy.

**Comment by niomaster** [comment]
And now?
