### ISSUE TITLE
Activity enrollment end date can be before the start date.

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#305]
The enrollment end date of an activity can be filled in to be before the enrollment start date. This confuses people because their enrollment does not work. We should add a form constraint to make sure the end date is after the start date.

**Comment by SebastiaandenBoer** [comment]
However, one should consider that time is non-linear. Therefore, from an individual's perspective the enrollment period could have an end date in the future even if the enrollment has been opened in the past already. Besides the fact that this statement only applies in a non-linear perspective-based flow of time, it is also completely non-applicable and irrelevant in the context of this project.
