### ISSUE TITLE
Calculating price when enrolling

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#309]
When I try to enroll for an activity with priced options, I should be able to see the total price (activity + options) at the bottom of the page. However, on staging and ia-beta, this calculating (done by jquery?) does not actually work. Thus it probably also does not work on live. 
One issue I found is that it calls a 'replace' method which is defined for Strings but not for a float/double on which it is actually called.
The price is correctly withdrawn from the person, just not shown correctly on the page where you select your preferences for enrollmentoptions.

**Comment by Sophietje** [comment]
Note: this seems to specifically occur when you have a checkbox with a price associated

**Comment by Sophietje** [comment]
Note 2: Make sure to test this for all templates/widgets who possibly also use prices.
Note 3: It was broken in Firefox 57.0.4, possibly also in other browsers

**Comment by SebastiaandenBoer** [comment]
This is a relatively easy fix as it is indeed the result of the string vs floats/ doubles. Therefore, it only needs to be cast to a String or the Float/Double needs to be handled differently in the calculation.

**Comment by SebastiaandenBoer** [comment]
This seems to be working on both production, staging as well as beta using both Chrome, Firefox and **even Edge**. Therefore, I'm closing this issue.
