### ISSUE TITLE
Can't manually enroll when controlled by OAuth application 

### ISSUE THREAD

**Issue by Yoeori** [Inter-Actief/amelie#310]
The committee should be able to manually enrol people for an event on the IA site, even though the event is controlled by an OAuth application. 

Right now the committee gets the error "Enrollment for [event] is only possible on the website of this activity." when trying to use the "Enroll people" button.

**Comment by Kurocon** [comment]
We won't fix this, this would result in a desynchronization between the enrollments on the IA website and the enrollments on the external website. This should be handled by the external application.
