### ISSUE TITLE
Possibility for 'virtual' ENIAC membership

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#313]
Members of our alumni association ENIAC are also welcome at our activities. During these activities, they can normally not use facilities like Alexia.

For this, we want the possibility to have an ENIAC membership. The ENIAC members are not really member of Inter-Actief, but can use the facilities we offer concerning payment.

**Comment by Kurocon** [comment]
The 'real' website now has an extra Membership Type (ENIAC) which you can give to ENIAC-members. This membership will last until the end of the association year, and will not be automatically prolonged. If you want it to be automatically prolonged, let me know and I'll update the script, but I think this is not a good idea, as you then need to explicitly end the memberships, which can be forgotten.

**Comment by WKobes** [comment]
Thanks! I am not sure why automatically prolonging is a problem. The membership does not equal a legal association membership and is just used to be able to access the payment facilities. In my opinion these memberships could be automatically extended.
