### ISSUE TITLE
Removal of narrowcasting models and admin hooks

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#317]
The narrowcasting module is currently a single page requesting various elements from the amelie:
- list of news
- list of upcoming activities
- gallery of pictures
- company banners

Supposedly, television promotions are not television banners and they do not seem to be used, neither do they seem to be working.

As we are currently working on translating the codebase and this feature does not seem to be used, it might be a better idea to remove it. I would like to stress that this does not seem to be affecting the current feature set of the narrowcasting page, nor does it impact API usage (which also needs to be adapted accordingly).

**Comment by windwarrior** [comment]
I can answer this! There's 'television banners' which are companies advertising on the television, these are displayed in the right-most carousel. Some committees, most notably the Pandora-committee, have requested the ability to promote on the screen as well and have dedicated slots in the _left_ carousel, these are called 'television promotions' and implemented in the narrowcasting module. Last time I tried something with it it still worked.

That said, the feature is a bit obscure and only accessible from the admin interface of amelie, I do think that the ability to promote on the television is valuable, but the current (*ehem* hack *ehem*) is a bit too limited and obscure.

**Comment by SebastiaandenBoer** [comment]
Considering we're already looking into redesigning the TV promotions with support for videos. I would argue that - as it is closely related to support for other media types - we would incorporate this into the TV redesign. Therefore, let me ping #77 

We would need to make a user interface for this though and adapt the JavaScript for this specific feature as it no longer seems to be working.
