### ISSUE TITLE
Let the photoviwer of the personal tab use the API

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#32]
This commit (https://www.inter-actief.utwente.nl/vcs/hg/www/amelie/rev/5cc761ebe34f) changed the way the photoviewer gets the images to the API, this has to be applied to the personal tab. The personal tab uses its own brandbox.js so that wasn't changed automatically.

**Comment by WKobes** [comment]
@Kurocon please verify if still needed since you revamped the PoS

**Comment by Kurocon** [comment]
Photo viewer does not use the API, but I don't think it needs to be changed.
