### ISSUE TITLE
Bulleted list lacks bullet formatting on education news overview page

### ISSUE THREAD

**Issue by Linths** [Inter-Actief/amelie#324]
I've just posted an education news message with a bulleted list. This is formatted properly on the [page of the specific message](https://www.inter-actief.utwente.nl/nieuws/350/2018/4/6/registration-research-project-module-11-bit-tcs/), but not on the [education news overview](https://www.inter-actief.utwente.nl/onderwijs/nieuws/).

Proper formatting:
![image](https://user-images.githubusercontent.com/9081617/38423697-ecbe85c0-39ae-11e8-9e9f-b4ed2c701c91.png)
Improper formatting:
![image](https://user-images.githubusercontent.com/9081617/38423735-111ef9c2-39af-11e8-8a00-3229854f373f.png)

Thank you!

**Comment by Kurocon** [comment]
Seems to be a small issue with either the css or the markdown rendering, but probably the first because the links are working properly.

**Comment by justinetroyke** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!
