### ISSUE TITLE
Update Privacy Policy

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#326]
The following changes need to be incorporated:
- [x] ~~New privacy policy body text needs to be added~~
- [x] ~~Enclose the body of the privacy policy in blocktrans~~
- [x] ~~Link to the GDPR document (in-progress) that should include all processes related to personal data (including a list of sub-processors)~~

**Comment by Kurocon** [comment]
Pretty easy fix once the text of the new policy and the document are done.

**Comment by SebastiaandenBoer** [comment]
We have decided to extend the current GDPR document website with a short statement on the top, indicating our general policy. If people wish, they can then read further, or go back. In any case, we want to omit any direct privacy page from the website.

**Comment by SebastiaandenBoer** [comment]
A new document has been drafted with a summary of the content (1/4 of the length of the actual amelie GDPR document). Some aspects of that can be reused if needed.

**Comment by SebastiaandenBoer** [comment]
Isn't this already live?

**Comment by Kurocon** [comment]
> Isn't this already live?

Yes, I think this is done.
