### ISSUE TITLE
Member Signup Changes

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#327]
As specified by the GDPR, the member signup form should:
- [ ] Require explicit consent to privacy policy and GDPR document on member signup
- [ ] Not allow anyone under the age of 16 to sign up (because of guardian's consent requirement)

**Comment by Kurocon** [comment]
Pretty easy; add a checkbox to the enrollment form and check it once it is sumbitted for the first point, add an age-check in the submission for the second and throw an error.

One does need to think about what to do if the guardians agree with the signup, and how to register the member properly then.
