### ISSUE TITLE
OAuth2 request form

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#328]
The website should preferably include a form where (external) parties can request an OAuth2 client_id and client_secret that sends an email to the WWW / SysAdmin committee. This form should include the following:

- [x] Application name
- [x] Member name
- [x] List of redirect URIs
- [x] Client type (confidential / public)
- [x] A short description of the intended purpose of the application

**Comment by Kurocon** [comment]
Pretty easy, just add a form with a view, and a processor to create a Django-oauth-toolkit Application object.

**Comment by windwarrior** [comment]
I am not sure whether you want to do this automatically tho… don’t you want the www to have the final say

**Comment by SebastiaandenBoer** [comment]
We could add an intermediate step that requires a super/ board to approve the request

**Comment by supertom01** [comment]
Instead of adding a link to the added request page to the navigation bar, the link can both be found in the API documentation and on the WWW wiki.
