### ISSUE TITLE
Kleur van nieuws in mail klopt niet

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#33]
De kleur van een nieuwsartikel zijn nu rood terwijl dit blauw moet zijn. Vergeet niet de juiste kleurtjes te gebruiken zoals in het huisstijldocument staat.

**Comment by J3173** [comment]
Gefikst met Inter-Actief/amelie-private#65 in Inter-Actief/amelie-private@4d9bbcc4326cf2cce30e20b0b9bde6428f71de7d door @Sophietje
