### ISSUE TITLE
Implement checkboxes for data processing activities

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#330]
In case of profiling (such as company-mailings, ~MSDNAA, DreamSpark~), there should be an opt-out on the profile edit page. Currently, there already exists an option for this on the member signup page with an associated database field, however, there is no opt-out after signup. This should be fixed.

**Comment by WKobes** [comment]
MSDNAA/DreamSpark are no longer on-site, thus the only profiling that exists is for company mailing. I therefore just changed the label of the current preference:

Ik wil informatie van bedrijven ontvangen. --> Ik wil gerichte informatie van bedrijven ontvangen.
I want to receive info about companies. --> I want to receive targetted info about companies.
