### ISSUE TITLE
Add warnings in comments

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#332]
The following scenario's should have HUGE warnings implemented as comments:

- [x] Updating the privacy policy should be communicated to members by email.
- [x] Updating the GDPR document should be communicated to members by email.
(additional warnings can be added based on codebase analysis)

**Comment by Kurocon** [comment]
Not very hard, but we do need to formulate the comments properly, and make sure everyone that reads them understands that they need to update documents if they change something.

Codebase analysis might be better for a separate ticket after we implement the basics of GDPR.

**Comment by SebastiaandenBoer** [comment]
This seems to be ready. Shall we close this and modify the progress on the primary Open Source ticket (#1).

**Comment by Kurocon** [comment]
Fixed in Inter-Actief/amelie-private#371
