### ISSUE TITLE
Export member data

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#334]
All members should be able to export their data in a machine-readable format. This data should be the same data collected in #333.

We have agreed upon the following process:

- A member can request their data once per day
- This triggers a background process that executes #333 and stores it for 24 hours
- Once the data is available, an email should be sent to the member informing about this event
- If a member requests their data within 24 hours since their last request, their cached data should be used instead of executing another background process

**Comment by Kurocon** [comment]
Is solved by solving #333 (practically the same ticket). I'll copy-paste this text into a reply there and close this ticket.
