### ISSUE TITLE
Deletion of member data

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#335]
All member data should be prone to deletion. Data should be obfuscated wherever it is not possible/ reasonable to delete it, such as transactions, mandates, etc.

**Comment by Kurocon** [comment]
Also a pretty big one. Basically every piece of information that can be retrieved in #333 should be obfuscatable to the level that is possible.

One of the edge cases to take care of is that someone can tell us to delete all their data, but we are legally required to keep the data (e.g. purchase data) for x amount of years, after which the data needs to be removed anyway.
