### ISSUE TITLE
Check license compatibility of libraries

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#339]
We need to check if the licenses of our libraries are compatible with the BSD license we want to release our code under.

**Comment by SebastiaandenBoer** [comment]
Babel --> BSD-3
Django --> BSD-3
Markdown --> BSD-3
Mastodon.py --> MIT
Paste --> MIT
Pillow --> Standard PIL License
PyJWT --> MIT
WebOb --> MIT
amqp --> BSD-3
anyjson --> BSD-2
asn1crypto --> MIT
beautifulsoup4 --> MIT
billiard --> BSD-3
bleach --> Apache Software License 
celery --> BSD-3
certifi --> Mozilla Public License 2.0
chardet --> General Public License (LGPL) 
cryptography --> BSD-3 / Apache
decorator --> BSD-2
defusedxml --> Python Software Foundation License (PSFL)
django-appconf --> BSD-3
django-auditlog --> MIT
django-braces --> BSD-3
django-celery-results --> BSD-3
django-ckeditor --> BSD-3
django-compressor --> MIT
django-counties --> MIT
django-debug-toolbar --> BSD-3
django-extensions --> MIT
django-formtools --> BSD-3
django-iban --> BSD-3
django-json-rpc --> MIT
django-jsonfield --> BSD-3
django-localflavor --> BSD
django-oauth-toolkit --> BSD-2
django-rosetta --> MIT
django-sslserver --> MIT
django-uuidfield --> BSD-3
djangsaml2 --> Apache Software License (Apache 2.0)
docutils --> BSD-2, GNU General Public License (GPL), Python Software Foundation License, Public Domain
fcm-django --> MIT
flower --> BSD-3
future --> MIT
google-api-python-client --> Apache Software License (Apache 2.0)
html5lib --> MIT
httplib2 --> MIT
icalendar --> BSD-2
idna --> BSD License (BSD-like)
kombu --> New BSD License
markdown2 --> MIT
microsofttranslator --> BSD License (BSD)
mysqlclient --> GNU General Public License (GPL)
oauth2client --> Apache Software License (Apache 2.0)
oauthlib --> OSI Approved, BSD License (BSD)
pip --> MIT
pkg-resources --> 
polib --> MIT
pyOpenSSL --> Apache Software License (Apache License, Version 2.0)
pyasn1 --> BSD-2
pyasn1-modules --> BSD-2
pycparser --> BSD-3
pycryptodomex --> BSD-2 License, Public Domain
pyfcm --> MIT
pyinotify --> MIT
pyldap --> No license --> Public Domain
pyrad --> BSD-3
pysaml2 --> Apache Software License (Apache License Version 2.0)
python-dateutil -->  Apache Software License, BSD License (Dual License)
python-gitlab --> GNU Lesser General Public License v3 (LGPLv3) (LGPLv3)
python3-openid --> Apache Software License
pytz --> MIT
raven --> BSD
reportlab --> BSD License
repoze.who --> BSD-derived
requests --> Apache Software License (Apache 2.0)
requests-oauthlib --> BSD-like
requests-toolbelt --> Apache Software License (Apache 2.0)
rsa --> Apache Software License (ASL 2)
setuptools --> MIT
six --> MIT
social-auth-app-django --> BSD-3
social-auth-core --> BSD-3
sqlparse --> BSD-3
tornado --> Apache Software License (http://www.apache.org/licenses/LICENSE-2.0)
twython --> MIT License
uritemplate --> BSD 3-Clause License or Apache License, Version 2.0
urllib3 --> MIT
vine --> BSD-3
wheel --> MIT
zope.interface --> Zope Public License (ZPL 2.1)

**Comment by SebastiaandenBoer** [comment]
The following questions remain:

- [ ] What to do with Mozilla Public License 2.0?
- [ ] What to do with Zope Public License (ZPL 2.1)?
- [ ] What to do with Standard PIL License (ZPL 2.1)?
- [ ] What to do with pkg-resources?

- [ ] Is BSD-3 compatible with GNU GPL licenses?

**Comment by SebastiaandenBoer** [comment]
So far, it seems best to license amelie under BSD-3 _as well as_ GNU GPLv3, although that is not specifically necessary. GPLv3 explicitly states that it is compatible with BSD-3, even if included in a larger work that is predominantly non-GPLv3. Please correct me if I'm wrong, but I think we can go with BSD-3.

**Comment by Kurocon** [comment]
Compatibility looks good, LICENSE.md with the BSD 3 clause license added in Inter-Actief/amelie-private#464
