### ISSUE TITLE
Remove old Oauth library

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#341]
Need to remove old Oauth library

**Comment by niomaster** [comment]
Progress is here: https://github.com/Inter-Actief/amelie-private/tree/oauth2_refactor

Todo:

[ ] Make a management command to expire tokens (24 hours-ish?)
[ ] Translations
[ ] Remove old library
[ ] Update profile (send oauth link target and mail template, add links to associate providers)
