### ISSUE TITLE
API should return first membership in the case of study-long memberships

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#342]
API should return first payment for membership (that is not 0) in the case of study-long memberships

**Comment by WKobes** [comment]
Take into account that some persons have a primary/secundary yearly membership now, while they have had a study long membership in the past.

**Comment by SebastiaandenBoer** [comment]
Looking at the app and the referenced issue, the issue no longer seems to be present. I'm therefore closing this and the referenced issue.
