### ISSUE TITLE
Clicking on search results for photo albums brings you to non-existing page

### ISSUE THREAD

**Issue by nielsedegroot** [Inter-Actief/amelie#344]
When you search using the search bar on the photo album page and then click one of the results, it gives you an error saying that page does not exist. The album can however be reached by just going through all of the pages with photo albums and then clicking it.

**Comment by Kurocon** [comment]
Fixed in https://github.com/Inter-Actief/amelie-private/commit/ca4788070def46079ff27d5d9be42d16a333baf2
