### ISSUE TITLE
Membership payment issues

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#345]
If there is no payment for a specific type of membership, then there's a certain issue with the website as seen in the screenshot. Also, the API will throw a Internal Server Error.

**Comment by SebastiaandenBoer** [comment]
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5831d5d8238c6a0e0029c17b/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f67c25d5b229ea147d550c571df8145e5f44fef08f78a6e32e6c981e5ab38532022d8c6853beb2901eb80bbb25894a80b4bf8944c7e03426f5c6.png)

**Comment by Yoeori** [comment]
@SebastiaandenBoer Do you have a working screenshot?

**Comment by SebastiaandenBoer** [comment]
Almost a year and a half later, I don't. Unfortunaltely, I also do no longer remember where this issue occurred. However, I can imagine that this had something to do with the studylong membership not having a payment for subsequent years. I cannot verify this on the moment.

**Comment by SebastiaandenBoer** [comment]
Pretty sure this was in some way related to #342

**Comment by SebastiaandenBoer** [comment]
Looking at the app and the referenced issue, the issue no longer seems to be present. I'm therefore closing this and the referenced issue.
