### ISSUE TITLE
Buttons/search function on Photo page not functioning correctly

### ISSUE THREAD

**Issue by Esloot** [Inter-Actief/amelie#346]
The photo album page has non functional First/Last/Next/Previous buttons. Apart from that, when searching for an album, clicking on it does not open the album, instead there comes a message that states that the requested page does not exist, and the URL has /None at the end. The album can be opened when just looking for it by going to the correct page, or by removing the "none" as the last part of the URL. (There has already been a ticket for this, but I am unsure if it was resolved in the meantime and reoccurred).

**Comment by Kurocon** [comment]
Paginator fixed in https://github.com/Inter-Actief/amelie-private/commit/a59d07e5e60149e39157bafb14210b307d0590f1

Photo links fixed in https://github.com/Inter-Actief/amelie-private/commit/ca4788070def46079ff27d5d9be42d16a333baf2
