### ISSUE TITLE
Reset user preferences

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#349]
All opt-out preferences need to be reset and then users need to indicate which options they are interested in again. We probably want to ask the board to send an email, or send an email ourselves, to all members when this has been done to notify the members of these changes.

**Comment by Kurocon** [comment]
Sebastiaan has researched this; If people have given consent under the old regulations, be it opt in or opt out, then we do not need to reset these preferences. So this ticket has become invalid.
