### ISSUE TITLE
Event helper tool should be redone for new utwente website

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#354]
The UT switched to a new event registration tool (https://www.utwente.nl/campus/organisatie/bijeenkomst-melden/). This tool however has no overview of already registered events.

We asked the UT if such an overview could be generated, the response was this:

> Antwoord op deze is helaas even blijven liggen, maar de oplossing is als volgt.
> 
> Vul bij de contactinformatie bij Afwijkend emailadres een algemeen email adres in. Alle bevestigingen worden dan daar naartoe gestuurd.
> 
> Als er meldingen aangepast moeten worden, en de oorspronkelijke melder is afwezig, graag contact met mij opnemen. Ik kan als beheerder altijd gegevens bijwerken.

So basically we should build something that reads mails to a specific address. This could then be used as data for the former 'evenementenhulpje'

**Comment by Kurocon** [comment]
Fixed by beuning something around an e-mail box
