### ISSUE TITLE
GPDR view of activity sorts on alphabetical order instead of enrolment #

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#359]
Active members that see the enrolments on an activity page, now see Member #XXX where XXX is the number of enrolment. However, the enrolments are sorted on alphabetical order instead of the actual number, making the ordering 1, 10, 11, 12, 13, ..., 2, etc.

**Comment by Kurocon** [comment]
Fixed in https://github.com/Inter-Actief/amelie-private/commit/bd1b323a661d0a2c3e9f0ace24ec793ba4218a1a
