### ISSUE TITLE
Activity enrolments view should also show names after giving a reason

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#361]
The new GPDR implementations now makes sure that a reason should be given before names can be seen by regular committee members. However, it would be nice if this reason could also be given to 'unlock' the former view instead of being forced to open the print view or export to csv.

**Comment by Kurocon** [comment]
Fixed in https://github.com/Inter-Actief/amelie-private/commit/bd1b323a661d0a2c3e9f0ace24ec793ba4218a1a
