### ISSUE TITLE
Complaint section: enable preview for comments

### ISSUE THREAD

**Issue by Linths** [Inter-Actief/amelie#372]
I'd like to be able to see a preview of my comment on a complaint. I oftentimes find myself removing my comments and re-entering them, as Markdown sometimes doesn't do what I want (let's blame Markdown). This process yields mail spam for the Education Committee.

**Comment by WKobes** [comment]
As a comment may be edited, deletion of comments is unnecessary. Proposal is to remove the notification when a comment is edited. This makes sense, as edits are only expected to correct information provided. New info will always be added later in the discussion.
