### ISSUE TITLE
Add sub tab in the task bar

### ISSUE THREAD

**Issue by Linths** [Inter-Actief/amelie#374]
In the task bar, there's a tab called Education. Could you add to the sub tab "News" redirecting to https://www.inter-actief.utwente.nl/education/news/ to the list (between Information and Activities preferably)?

**Comment by Kurocon** [comment]
Fixed in https://github.com/Inter-Actief/amelie-private/commit/08240176a9c4c279a3da936b0e7af2fe481980d1
