### ISSUE TITLE
Uitzoeken of vertaalde velden van Event en Nieuwsbericht nog onjuist gebruikt worden

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#38]
Recent zijn een aantal velden in Event en Nieuwsbericht vervangen door andere velden om vertaling mogelijk te maken, bijvoorbeeld samenvatting werd samenvatting_nl en samenvatting_en. samenvatting is hierbij een property geworden die automatisch het waarde van het veld voor de huidige taal oplevert.

Nagekeken moet worden of de plaatsen waar nog de oude velden gebruikt worden, dit nog echt kan. Wat niet kan is bijvoorbeeld sorteren op het oude, niet echt bestaande veld of url's genereren op basis van dit veld, omdat die dan wisselen met de geselecteerde taal.

Voorbeeld al gefikst probleem: ​https://github.com/Inter-Actief/amelie-private/commit/9188634f34e0f07f8295295e3f7d59187f7542fd

**Comment by J3173** [comment]
Waarschijnlijk zijn alle problemen hiermee ondertussen al opgelost.
