### ISSUE TITLE
Return only former members filter does not work properly

### ISSUE THREAD

**Issue by SebastiaandenBoer** [Inter-Actief/amelie#382]
When only selecting "Return former members", all (former) members with at least one Membership are returned
When only selecting "Only return former members", no members are shown
When selecting both options, all (former) members except those with only a Membership in the current year are selected.

Expected behaviour:
When only selecting "Return former members", all (former) members with at least one Membership are returned
When only selecting "Only return former members", only former members with at least one Membership are returned
When selecting both options, only former members with at least one Membership are returned (but this option may also be removed, for instance using a radio box/dropdown etc)

**Comment by Quitlox** [comment]
I'll leave this issue for now for our new members as an easy-to-fix :P

For whoever is going to look into this, the relevant query fields can be found at `amelie/members/query_forms.py:42` and the handling at `amelie/members/query_forms.py:167`.

I suggest indeed replacing these two separate options with radiobuttons with something like a DJango ChoiceField.
