### ISSUE TITLE
Direct debit translation issue

### ISSUE THREAD

**Issue by Yoeori** [Inter-Actief/amelie#397]
The email send to members for a direct debit contains a link to the direct debit which isn't translated yet: https://www.inter-actief.utwente.nl/streeplijst/incassoinstructie/xxxx/, which should be https://www.inter-actief.utwente.nl/personal_tab/debt_collection_instruction/xxxx/.

**Comment by WKobes** [comment]
Duplicate of #402, which is fixed in a PR
