### ISSUE TITLE
Complaint section: edit text of the complaint filing part

### ISSUE THREAD

**Issue by Linths** [Inter-Actief/amelie#398]
To encourage complainants to file their complaints in English, I'd like to have the following texts updated.

##Dutch
Please add
"**Geef gelieve je klacht in het Engels zodat andere studenten het (later) kunnen begrijpen. Mocht je dit liever in het Nederlands doen, dan is dat ook ~~mogelijk~~prima.**"
to
"Vertel ons helder wat er aan de hand is en welke acties je al ondernomen hebt om iets aan je probleem te doen (bijvoorbeeld het e-mailen van de docent of de modulecoordinator). Geef ook aan wie de docent is van het vak, en als het gaat om een verlopen nakijktermijn, laat ook weten wat de datum van de toets of de deadline van de opdracht was.".

This gives the following total text:
"Vertel ons helder wat er aan de hand is en welke acties je al ondernomen hebt om iets aan je probleem te doen (bijvoorbeeld het e-mailen van de docent of de modulecoordinator). Geef ook aan wie de docent is van het vak, en als het gaat om een verlopen nakijktermijn, laat ook weten wat de datum van de toets of de deadline van de opdracht was.
**Geef gelieve je klacht in het Engels zodat andere studenten het (later) kunnen begrijpen. Mocht je dit liever in het Nederlands doen, dan is dat ook mogelijk.**"

##English
Please add
"**Preferably describe your complaint in English to make sure other students can understand it (later). In case you'd rather do this in Dutch, that's fine as well.**"
to
"Please state clearly your problem and the actions you have already taken to solve it (for example, e-mailing the teacher or module coordinator). Also include the name of the teacher of the course. If the complaint is about an exceeded marking period, be sure to state the date of the test/assignment deadline."

Giving the total text:
"Please state clearly your problem and the actions you have already taken to solve it (for example, e-mailing the teacher or module coordinator). Also include the name of the teacher of the course. If the complaint is about an exceeded marking period, be sure to state the date of the test/assignment deadline.
**Preferably describe your complaint in English to make sure other students can understand it (later). In case you'd rather do this in Dutch, that's fine as well.**"

Thank you!

**Comment by Kurocon** [comment]
Edited "mogelijk" in first dutch paragraph to "prima", as per advisement of Jotte and Wouter. Furthermore, we'll fix it as soon as we have time!
