### ISSUE TITLE
Room duty tool: edit schedule viewing rights

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/amelie#399]
I had sent an email about this recently, we'd like it if the individual schedules in the room duty tool could only be seen by the people who are in the schedule.

(Just remove board viewing rights?)

**Comment by niomaster** [comment]
I still do not understand why this is necessary. Do we really want to have objects in the website which cannot be accessed/administered by anyone?

**Comment by jeffreybakker** [comment]
I don't mind it either, but I was told to create a ticket for it. If you do not want to do it just discard this ticket
