### ISSUE TITLE
Uniformiseren namen views

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#4]
Als je naar de ledenadministratie wilt zou dat eigenlijk iets als amelie.leden.views.home moeten zijn. Dat maakt het makkelijker om er naar te verwijzen in templates via de {% url %}-tag

In de huidige ledenadministratie zijn bijvoorbeeld een aantal functies verdeeld over meerdere views-files, om de losse files "overzichtelijk" te houden. Echter verwart die indeling ook.

**Comment by Tijnoz** [comment]
Views zijn nu al anders genoemd via de nieuwe URL scheme. Woei.
