### ISSUE TITLE
HTML tags worden niet gerenderd

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#41]
Bijvoorbeeld de pagina ​https://www.inter-actief.utwente.nl/nieuws/128/2012/3/26/onderwijsupdate-11/. Er verschijnen HTML tags die niet als HTML worden gerenderd.

**Comment by J3173** [comment]
HTML-tags zijn op een gegeven moment uitgeschakeld in nieuwsberichten en bij activiteiten. Oude nieuwsberichten en activiteiten, zoals dit bericht uit 2012, bevatten soms nog HTML, terwijl dit niet meer mag. Wat mij betreft is het niet nodig deze oude berichten en activiteiten aan te passen.

**Comment by SebastiaandenBoer** [comment]
Kunnen we deze issue sluiten?

**Comment by Kurocon** [comment]
Eensch. Gesloten want wontfix

**Comment by windwarrior** [comment]
Het probleem hier is dat commissies soms nieuwsberichten kunnen aanmaken,
en daarmee een xss lek hebben in de website. Er is dan ook gekozen om
alleen markdown toe te staan in alle velden waar "normale" gebruikers
toegang tot hebben, bijvoorbeeld bedrijven ondersteunt nog html, om de
extern van de vereniging niet helemaal gek te laten worden ;).

--Lennart

2017-02-16 19:28 GMT+01:00 Kevin Alberts <notifications@github.com>:
