### ISSUE TITLE
Incorrect error message given when changing activity description

### ISSUE THREAD

**Issue by nielsedegroot** [Inter-Actief/amelie#410]
Website gives an error saying no English summary was given even if it was actually given.

![image](https://user-images.githubusercontent.com/23638329/45812904-78763680-bcd1-11e8-8e7f-c42c91c186a3.png)

**Comment by WKobes** [comment]
This error message probably referred to the title of the activity. The title is called 'summary' in the codebase, which might not be the best term to use here. However, for sake of consistency, I close this issue as the error is not incorrect.
