### ISSUE TITLE
People with a double membership (even canceled ones) appear twice in the birthday list

### ISSUE THREAD

**Issue by nielsedegroot** [Inter-Actief/amelie#411]
Membership was changed from yearlong to studylong but it seems there are now two instances of this member and he/she thus shows up twice in the birthday list.

![image](https://user-images.githubusercontent.com/23638329/45831746-72e41500-bd00-11e8-8a66-9de1bc0371ff.png)

**Comment by PietPtr** [comment]
Cannot reproduce, there is a .distinct() after the query so this should be impossible.
