### ISSUE TITLE
Inloggen streeplijst gaat soms stuk

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#42]
Zowel het handmatig inloggen als bij het aanmelden van nieuwe kaarten geeft de streeplijst fouten bij het inloggen (lijkt voornamelijk bij inloggen met S-nr).

Dit resulteert soms in de foutmelding dat de inloggevgevens fout zijn en soms in een wwergave van de IA-website met een melding dat er iets fout is gegaan met CSRF.

Gaat er iets stuk in onze API? (verder geen foutmeldingen in Sentry/ andere logging kunnen vinden)

**Comment by Kurocon** [comment]
This is the result of the CSRF token expiring. A periodic refresh on the main page of the streeplijst might fix the issue.
