### ISSUE TITLE
Member search export gives empty result set in staging/beta

### ISSUE THREAD

**Issue by Yoeori** [Inter-Actief/amelie#430]
When exporting a set of members at `/members` to CSV it returns a file without any results.

This was tried with the following settings applied:
- Study year: 2018
- Studies: `B-BIT,B-CS`

**Comment by PietPtr** [comment]
This is only about beta and staging, this does work properly in production. This is probably due to a bug in the Django run server.

**Comment by WKobes** [comment]
Appears to be fixed by the same solution as for #522
