### ISSUE TITLE
Reminder for personal mail address in membership form

### ISSUE THREAD

**Issue by WesselAmmerlaan** [Inter-Actief/amelie#437]
Often people fill in their student mail as contact mail in the membership form. If people use their student mail, they cannot be contacted again after leaving the university. 

Although board members often point this out, it might be forgotten and hence a fitting reminder on the page itself.

**Comment by Kurocon** [comment]
"We urge you **not** to use your student mail, because this e-mail address will expire after you stop studying, leaving us unable to contact you in the case of important changes regarding your membership"

**Comment by WKobes** [comment]
The help text was already rather long, so I appended: "We recommend you to use a personal email address, since your student email will stop working when you graduate."
