### ISSUE TITLE
Company corner images fixed size

### ISSUE THREAD

**Issue by eggied97** [Inter-Actief/amelie#438]
[Please write your issue in English]
Hi WWW,

Now the companies provide their own logos and we don't really have restrictions on it. 
Is it possible to set some sort of fixed height/width/ratio/something on the company logo's so that it all is a bit more uniformly?

Thanks!

xxx,
Egbert

**Comment by WKobes** [comment]
Marking this as wontfix. Priority is very low and as only the external affairs will upload these images, uniformity can be guaranteed easily.
