### ISSUE TITLE
Microsoft Imagine is renamed to Azure Dev Tools for Teaching

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#446]
Imagine is being renamed, so we need to update our link. See text below (in dutch)

---

Uw huidige Imagine-abonnement wordt op maandag 11 februari 2019 automatisch overgezet naar een Azure Dev Tools for Teaching-abonnement. De enige wijziging voor uw abonnement is de naam en de locatie waar studenten en de faculteit toegang krijgen tot de abonnementsservices.

**Aanbevolen actie**
Gebruik vanaf maandag 11 februari 2019 de URL https://aka.ms/devtoolsforteaching wanneer u een koppeling wilt geven naar abonnementsservices. Anders geeft uw huidige Imagine-webstore een omleidingskoppeling weer om naar uw nieuwe hub te gaan.

**Comment by WKobes** [comment]
Fixed in Inter-Actief/amelie-private#7fd235b85fce7223f298898efdc8a15a8ca1f76b
