### ISSUE TITLE
Remove MSDNAA app (from frontend)

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#452]
Let's discuss:

The MSDNAA application is obsolete due to Microsoft Imagine. It can therefore be deleted.

Facts:
- (almost) all keys are depleted
- key-less applications are outdated
- takes up a large part in the front-end 'for members' menu.

Things to think about:
- People who currently have a key might want to be able to access them. We could make them available in a special part of the profile (only for those who have keys) or email them once before removal of the app

Opinions?

**Comment by AVeenstra** [comment]
Email the keys and then remove the app and files after xx days.
