### ISSUE TITLE
Upload new version of the HR to the website

### ISSUE THREAD

**Issue by nielsedegroot** [Inter-Actief/amelie#456]
At the GMM of September 4th, 2018, a change in the House Regulations of our association has been accepted. The changed document now needs to be uploaded to the website on inter-actief.net/alv. The documents will be send to the WWW committee by e-mail, since these documents are internal and are not be shared with the WWW (World Wide Web ;p).

**Comment by Yoeori** [comment]
Solved in Inter-Actief/amelie-private@5eaed128b3ab77f38696a49f594eb996731611bc
