### ISSUE TITLE
Mention allergy information at the food order screen

### ISSUE THREAD

**Issue by WesselAmmerlaan** [Inter-Actief/amelie#458]
It would be nice if the page where you select food explicitly states that any serious allergies should be send to the committee (instead of adding an extra form) for activities that order from the standard restaurants

**Comment by Kurocon** [comment]
We can add a text pretty easily, but isn't it better to just add the extra field because people can then indicate the details themselves instead of having to send a separate e-mail?

**Comment by Kurocon** [comment]
We could also look into providing the allergy information with the products themselves, and then show it when people are selecting the food.
