### ISSUE TITLE
Add filters to activities list

### ISSUE THREAD

**Issue by niomaster** [Inter-Actief/amelie#460]
From Sander Meinderts, 16/04/2019:

Wouldnt it be nice if on the inter-actief website there would also be a box which lists the activities for which one can enrol.

E.g. right now you have to scroll down to the 16th of May to find the enrolment for the 11-beers unit, whereas it would be more practical if it would be immediately shown on the front page.

**Comment by niomaster** [comment]
I think this is a good idea. Maybe it is also worth considering whether we should give priority on the frontpage to recently-opened activities or something, perhaps at the top with an "open" badge or something like that.

**Comment by ljonja** [comment]
Why would you need to make a separate list (whether or not within a box) for this? Wouldn’t it be more efficient to mark those activities in the already existing list as being open for enrollment?
One could also make filters (probably as buttons) for the already existing list.

**Comment by Kurocon** [comment]
Indeed, adding filters to the main activities list on https://www.inter-actief.utwente.nl/activities/ seems like the way to go. Also, adding an icon on the front page if enrollment is open can also be a good improvement.
