### ISSUE TITLE
Add way to pre-enroll new members by do-group parents

### ISSUE THREAD

**Issue by niomaster** [Inter-Actief/amelie#468]
_From Denise den Hartog_:

Since we have thrown over the do-group market completely, the kiddos will now sign up for Inter-Actief before they have chosen a do-group. If I'm correct, the current sign up form for freshman asks for their do-group. 
Could something be changed about this so the kiddos can sign up before they know their do-group?

**Comment by niomaster** [comment]
I think this issue should also include some UI to set the dogroup of kiddo's in batch form, as doing that via admin is not tenable.

**Comment by Kurocon** [comment]
Zoals net met Kevin overlegt willen we het inschrijven van de kiddos komende kick-in iets veranderen. In tegenstelling tot mijn vorige mail, willen we nu de ouders verantwoordelijk maken voor het inschrijven van de kiddos. Dit zal dus niet meer gebeuren tijdens de doegroepenmarkt. De doegroep selectie hoeft dus niet meer uit het formulier gesloopt te worden.
Hier moet echter nog wel wat voor veranderen, namelijk dat de doegroepouders hun kiddos moeten kunnen inschrijven. Dit zullen de ouders met hun kinderen doen voor de bachelor dag, zodat op de bachelordag de formulieren kunnen worden ondertekent.
