### ISSUE TITLE
Revise education app

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#469]
This is a master issue for revising of the education app. Several issues are currently open concerning the app and the full codebase should be revised.

Open issues:

- [ ] #424 
- [ ] #423 
- [ ] #408
- [ ] #415 
- [ ] #372
- [ ] #417 
- [ ] #416
- [ ] #48 
- [ ] #35
- [ ] #36

**Comment by Kurocon** [comment]
Created a milestone to track this.

https://github.com/Inter-Actief/amelie/milestone/7
