### ISSUE TITLE
Links in HTML van API moeten absoluut zijn

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#47]
Op sommige plaatsen binnen de API zit HTML, onder andere bij het nieuws en binnen de bedrijven. Binnen Android wordt die HTML weergegeven in een WebView?, waarbij de baseURL gezet wordt op ​https://api.ia.utwente.nl:443/app/lennart/. Dat betekent dat als er URL's in de HTML staan van de vorm '/pad/naar/mijn/bestand.ext' dat die dan van api.ia.utwente.nl geladen worden. Daar gaat echter stuk op het volgende nieuwsitem: ​https://www.inter-actief.utwente.nl/nieuws/243/2015/4/10/23-april-is-de-minormarkt/. Hier staat namelijk een URL zonder domein in. Klikken op die link binnen de Android app leidt de gebruiker naar ​https://api.ia.utwente.nl:443/documenten/ond... enz, en dat bestand bestaat niet.

Ik stel daarom voor dat binnen de API de URL's een domein meekrijgen als dat niet api.ia.utwente.nl is.

---

Dit probleem wordt op dit moment met een hack afgevangen in Windows Phone, maar ook hier zien we graag verbetering van de API.

**Comment by windwarrior** [comment]
@dexbleeker Dit moet jouw ticket zijn, weet je toevallig waar dit exact mis gaat? Alleen nieuws of meer plekken?
