### ISSUE TITLE
Page /companies/activities/old/ does not display any data

### ISSUE THREAD

**Issue by Quitlox** [Inter-Actief/amelie#471]
On the page /companies/activities/ one can view some of the past external activities. As of writing, the most recent activity stems from 2018. The page /companies/activities/old/ contains a form to select a date range in which to view activities. No matter how big the range, zero results are shown.

**Comment by WKobes** [comment]
This is due to the 'visible_to' field, the dates have passed for the given activities. In the other overview, invisible activities are visible for people with board rights.
