### ISSUE TITLE
private pictures on website available for non-members

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/amelie#477]
Pictures on the Inter-Actief-site that are marked as private can be seen by anyone who can log in on our website using their UT-account. However, when logging in, there is never a check whether the person is actually a member of our association, which allows them to log in and view these pictures.

**How to replicate?**
The pictures of the [Cantus XII](https://www.inter-actief.utwente.nl/activities/6041/photos/) are only available for logged in users.

1. Find someone who is not member of IA (ie. Sjoerd from Scintilla)
2. Ask them to log in on our site using their UT credentials
3. Let them visit [Cantus XII](https://www.inter-actief.utwente.nl/activities/6041/photos/)
4. The pictures are now visible, while the logged in user is not a member.

Next to that, the user can do the following other things:

- Add more login options under profile
- View the complaints on the homepage
- View the birthdays on the homepage
- View private video's on the homepage

**Possible solutions**

1. **(preferred)** add a check when logging in whether the user is actually a current member (after validation from radix (or whatever it is called) of course).
2. block off every single one of those possibilities mentioned above

**Comment by Yoeori** [comment]
I tested this with an account which is not and has never been a member of Inter-_Actief_, and did not encounter this problem. The website correctly shows a page informing you no account exists for this profile and asks you to 'Log out'.

I'm guessing this is only a problem for users which have in the past been a member of IA and can therefore login.

**Comment by jeffreybakker** [comment]
Have you also tried directly opening the URL (as pasted in the description) with that account? Because the person I tested this with had never been a member of Inter-Actief.

Furthermore, have you also tried any of the other actions that should not be possible?

**Comment by Yoeori** [comment]
You're correct that the photo's page is indeed available for some reason. I'll change it so that it automatically logs someone out who doesn't have a valid membership.
