### ISSUE TITLE
Deanonimizing comment on complaint

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#48]
~~Op dit moment is een klacht achteraf niet meer te deanonimiseren en dat is bij deze ​klacht (https://www.inter-actief.utwente.nl/onderwijs/klachten/313/) foutgegaan, zodat Arends reactie onzichtbaar bleef.~~

At this moment it is impossible to deanonimize a complaint which went wrong for this ticket (https://www.inter-actief.utwente.nl/onderwijs/klachten/313/), which resulted in Arend's comment staying invisible.

**Comment by WKobes** [comment]
Marking this one as wontfix. If a comment needs to be de-anonymised, WWW-supers can handle it. As this will not happen often, I do not see a purpose in adding this feature.
