### ISSUE TITLE
Picture thumbnail plain white when file name contains quote

### ISSUE THREAD

**Issue by Quitlox** [Inter-Actief/amelie#483]
An example can be seen currently in the photo album of the Farmers Fair.

So apparently, when the filename of a photo contain a quote character for some reason, it messes up the css/html causing the image not to be found/drawn.

A solution would be to disallow this character in filenames. Another solution would be looking into escaping these characters, however I am not sure whether this is easily done.

**Comment by MartijnVerkleij** [comment]
Yo! URL-escaping `'` characters with `%27` seems to solve the problem on Firefox. (however, I do not see how this would not work in other browsers.)

**Comment by SimplyPancake** [comment]
@WKobes Why was this reopened? Could you describe what is not exactly working?

**Comment by WKobes** [comment]
See https://github.com/Inter-Actief/amelie-private/pull/445

The PR that fixed the original issue was reverted. That is why this was reopened.

However, this is no longer relevant since https://github.com/Inter-Actief/amelie-private/pull/585
