### ISSUE TITLE
add an e-mail notification whenever someone is charged into / decharged from a committee

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/amelie#489]
add an e-mail notification whenever someone is charged into / decharged from a committee so that:

- the active member will get an active notification whenever their activism status is updated
- the board has an overview of who they need to charge into or decharge from a committee in their board meetings

**Acceptance criteria:**

- The active member gets an e-mail whenever he/she added to a committee:
  - If the member was not active before, then he/she will be notified of:
    - The privacy policy concerning active members
    - How to log into their IA mail account or how  to forward it to their personal mail
  - (optional) Merge with the notification when members become inactive
- The board gets an e-mail whenever someone is new to a committee or leaves a committee
- The mails will be sent at the end of the day so that function changes (new entries in committee membership) will not send unnessesary e-mails

**Comment by PietPtr** [comment]
Als bestuur graag wil dat we dit toevoegen doen we het, maar in principe lijkt het ons onnodig, aangezien de enige keer wanneer het relevant is is wanneer je voor het eerst actief wordt en dan krijg je al een mailtje over je actieveledenaccount.
