### ISSUE TITLE
New page for Social Media

### ISSUE THREAD

**Issue by denisedh** [Inter-Actief/amelie#496]
Dear WWW,

We would like to have a page added to the website where we can have an overview of all of our social media. The best place for this we think would be under 'for members'. Could you add this for me?

**Comment by Quitlox** [comment]
We would also like a new block on the frontpage of the website for social media. This block could contain the following text:

**Social Media**
Follow Inter-Actief on Social Media!
Snapchat: inter-actief
Instagram: inter.actief

Or join our gaming servers!
Discord: https://discord.gg/MZycq
Minecraft: minecraft.inter-actief.net

**Comment by Quitlox** [comment]
Bij deze de pagina
https://www.inter-actief.utwente.nl/about/31/social-media/

**Comment by Quitlox** [comment]
nvm, deze graag
https://www.inter-actief.utwente.nl/about/30/social-media/
