### ISSUE TITLE
Dubbele namen bij inschrijving activiteit door commissie

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#50]
Als ik naar Pieter zoek weet ik niet welke Pieter ik moet hebben 

-----------------------------------------------------------

Dit betreft waarschijnlijk wanneer een commissie iemand wil inschrijven voor de activiteit. Hier kunnen dan oud-leden(?) in komen die waarschijnlijk vaak niet nodig zijn. Een mogelijkheid is om een vinkje bij het formulier te maken om aan te geven dat je ook tussen de oud-leden wil zoeken of de resultaten sorteren zodanig dat oud-leden onderaan komen te staan.

**Comment by Tijnoz** [comment]
Has been fixed previously. kusjes
