### ISSUE TITLE
Photos query does not work as expected.

### ISSUE THREAD

**Issue by Magnificus36** [Inter-Actief/amelie#503]
When I type "doegroep" into the search bar on the [photos page](https://www.inter-actief.utwente.nl/activities/photos) the albums are filtered on album name as expected.
However, why I hit [Enter] / go to the URL with [`?q=doegroep`](https://www.inter-actief.utwente.nl/activities/photos/?q=doegroep) added, the albums seem not to be filtered at all.

**Comment by supertom01** [comment]
Closed by #838
