### ISSUE TITLE
Add link "What is a GMM" to GMM page

### ISSUE THREAD

**Issue by Quitlox** [Inter-Actief/amelie#512]
I wrote a document explaining what exactly a GMM is for those who don't know or want to attend their first GMM. I would like a link to be added to this document on the inter-actief.nl/gmm page, where the by-laws and house regulations are also located. As far as I can see, I cannot do this myself.

https://docs.google.com/document/d/1shWxaaE7OGvGNaJe8r2cG_11e63rzTvlhiNsbXMZe4s/edit?usp=sharing

**Comment by WKobes** [comment]
Please make a document in the Inter-Actief corporate identity template, and upload the PDF via FTP to the folder documenten/alv so we can link it from our own website.

**Comment by Quitlox** [comment]
I have updated the document and uploaded it to:
documenten/alv/What%20is%20a%20GMM%20%5BHuisstijl%5D.pdf
