### ISSUE TITLE
Add link to studystore book webshop to menu

### ISSUE THREAD

**Issue by daniquel** [Inter-Actief/amelie#513]
As we are taking over the booksales from IAPC, a link towards the studystore webshop needs to be placed on our website.
We would like to have the link to the webshop be a separate link in the drop down menu under the 'Education' tab if possible.
The link to the webshop is: https://interactief.itdepartment.nl/

**Comment by Kurocon** [comment]
This is quite easy to fix, but before we do so, is it ready to be put public? When I visit the webshop the text is still a bit weird and there are links to alembic in it. 

Also, don't forget to update the education page yourself if it is ready. https://www.inter-actief.utwente.nl/education/#boeken-kopen

**Comment by daniquel** [comment]
The creators of the webshop know, apparently they forgot they needed to change a bit more than just the name of the webshop. I was promised it will be fixed in the next week. So after that it can go online!

**Comment by Kurocon** [comment]
@daniquel It looks like most issues with the store page have been fixed, but it still has a link to alembic on there under the "We'll buy your books back" section. Sould we just make the changes or should we wait for a bit longer?

**Comment by Quitlox** [comment]
We also noted this mistake and @daniquel had already sent an email about this. Unfortunately our contact person is on vacation, but that should not delay the roll-out of this change. Could you add the link nevertheless?

**Comment by Kurocon** [comment]
@daniquel @Quitlox The changes have been merged and are online. I've also taken the liberty of updating https://www.inter-actief.utwente.nl/education/#boeken-kopen as well.
