### ISSUE TITLE
Filtering members based on study leads to unexpected email export behaviour

### ISSUE THREAD

**Issue by gilians** [Inter-Actief/amelie#522]
In the member database search, it is possible to filter members based on what they are studying. This works as expected in the online HTML overview, but exporting those results' email addresses leads to unexpected behaviour. What is expected, is that the number of email addresses in the export matches the number of members shown in the results.  However, the exported CSV contains a much larger number of email addresses (thousands).

**Comment by WKobes** [comment]
Seems to hold for all fields with a choice of objects. It causes a fielderror saying you are making an invalid choice, which in turn makes `query_form.is_valid()` return False in method `filter_query`. Should at least raise an error there.

**Comment by WKobes** [comment]
Turned out that the mistake was the use of a `dict`, instead a `QueryDict`
