### ISSUE TITLE
Adopt a Coordinated Vulnerability Disclosure policy

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#523]
As recommended by the [National Cyber Security Centre](https://www.ncsc.nl/aan-de-slag/coordinated-vulnerability-disclosure-beleid), we should adopt a CVD (formerly known as Responsible Disclosure) policy. This allows ethical hackers to report vulnerabilities without the risks of legal prosecution. The specific scope and terms can be decided upon by ourselves.

Adopting such a policy should only be done in consultation with the board.

--

Kurocon 2022-10-31: New link https://www.ncsc.nl/onderwerpen/cvd-beleid

**Comment by Kurocon** [comment]
Security.txt was added in https://github.com/Inter-Actief/amelie-private/commit/67ba1776d5bfa4e2e028803e1b758df8b02b48ad

CVD policy should still be written at some point, in conjunction with the board, but at least people know how and where to find us now.

**Comment by WKobes** [comment]
Sent a proposal to the board

**Comment by WKobes** [comment]
BTW: Once CVD is accepted, we should still:

- [ ] Add link on website (footer)
- [ ] Add Policy field in security.txt
- [ ] Add SECURITY.md to code base (GitHub security advisory)

**Comment by Kurocon** [comment]
SECURITY.md added in https://github.com/Inter-Actief/amelie-private/commit/ef25118669ed70fd4eb4ebf3de969d51d9ff51a2
