### ISSUE TITLE
Update access management system of UT to new IdP

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#528]
Email of 10/03/2021

> You are registered as a contact person for one or more webapplications that are using the Identity Provider (IdP) of the University of Twente. By using our IdP users of your application can login with their UT username and password.
> 
>  
> 
> We are migrating to a new access management system and the current system will not be available anymore for SAML based authentication after July 1st 2021.
> 
>  
> 
> The new system also offers Multi Factor Authentication (MFA). The use of MFA is mandatory for all UT-employees.
> 
>  
> 
> We offer you the possibility to switch to our new system but we need your help. The metadata for the IdP and SP (the Service Provider that's running on your site) needs to be renewed. This means that you will have to import a new xml file for the metadata of our new IdP and we will have to import the latest metadata of your SP into our new system.
> 
>  
> 
> If you no longer want to use our IdP, you don't have to do anything. The service automatically stops after July 1st 2021.
> 
>  
> 
> if you do want to migrate to our new IdP, please reply to this mail with the name and URL of the webapplication(s) you want to keep. We will then send you an email with further instructions. Please take into account that we are in the process of migrating over 100 applications to our new system before July 1st. So make sure you respond as soon as possible. Then we can plan the migration of your webapplication in time and guarantee continuous operation of our service.
> 
>

**Comment by Kurocon** [comment]
Sent our metadata to the UT, waiting for a reply with their metadata.

**Comment by Kurocon** [comment]
Received test environment metadata. Configured on staging, waiting for LISA to test it and send us the production metadata.

**Comment by Kurocon** [comment]
LISA tested and accepted it. They expect to get the production request ready in around 1-2 weeks (there are a lot of requests at the moment).

**Comment by WKobes** [comment]
@Kurocon was this issue completely resolved (on all apps, all environments?)

**Comment by Kurocon** [comment]
Finalized in https://github.com/Inter-Actief/amelie-private/commit/b421aa62168a8e06edf9a394930984ed27488f92
