### ISSUE TITLE
[GitHub API] Deprecation notice for authentication via URL query parameters

### ISSUE THREAD

**Issue by pieter-bos** [Inter-Actief/amelie#541]
Github emails us the following every now and then:

> Hello there!
> 
> On May 14th, 2021 at 19:06 (UTC) your application (I.C.T.S.V. Inter-/Actief/) used an access token (with the User-Agent python-requests/2.22.0) as part of a query parameter to access an endpoint through the GitHub API.
> 
> https://api.github.com/user
> 
> Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.
> 
> Depending on your API usage, we'll be sending you this email reminder on a monthly basis.
> 
> Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

If I had to guess that's probably the social auth module in the website, hence the issue here. I put an issue now because this authentication method is now really going away, see here: <https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/>. In short: as of may 5 the authentication method (deliberately) intermittently fails, and will be removed september 8.

**Comment by Kurocon** [comment]
I presume this is fixed since we moved to the new login system.
