### ISSUE TITLE
Logging in to mailing@inter-actief.net Gmail-account leads to SAML2-error

### ISSUE THREAD

**Issue by gilians** [Inter-Actief/amelie#542]
STR:
- Enter mailing@inter-actief.net while trying to sign in to Gmail (or enter the email address of supposedly any account without an actual IA-user attached to it).
- Get redirected to the Inter-Actief authentication flow.
- Log in with the correct Inter-Actief account credentials.

Results:
- Expected: get redirected to Gmail, logged in as the correct Inter-Actief user.
- Actual: the following SAML2-error at the URL [https://www.inter-actief.utwente.nl/saml2idp/login/process/](https://www.inter-actief.utwente.nl/saml2idp/login/process/)

```
Error during SAML2 authentication

NameError
name 'user' is not defined
```

This issue is of high importance, as it prevents us from sending company mailings.

**Comment by Kurocon** [comment]
Fixed in https://github.com/Inter-Actief/amelie-private/commit/40ab531a086ee4f80208e0bcfe6060a193b2ee81
