### ISSUE TITLE
Sending OAuth mail gives an internal server error

### ISSUE THREAD

**Issue by jellemaas** [Inter-Actief/amelie#543]
Pressing the OAuth link in the mail does work when a member was a student at the university. When the person who presses the OAuth link was/is never a member of the UT it gives an internal server error. Normally the OAuth mail does work with members who are old students of the UT, but when they are not a member of the UT it gives an internal server error

**Comment by Kurocon** [comment]
This may work properly these days because of the new login system. Not sure though, needs to be tested.

**Comment by supertom01** [comment]
Works now
