### ISSUE TITLE
Rename file uploads to prevent file name collision and iteration

### ISSUE THREAD

**Issue by WJ44** [Inter-Actief/amelie#549]
Recent events have made it clear that when in separate batches photos are uploaded with the same name things go wrong(sorry 😅). Perhaps it would be a good idea to, on upload, rename everything to a standard format something like [activityname]-## where already uploaded files are taken into account.

edit: Perhaps at least checking if the file already exists is a good idea so we don't get unfortunate internal server errors.

**Comment by WKobes** [comment]
Using a UUID in filenames would provide collisions and reduce possibilities for file iteration.
