### ISSUE TITLE
TLDR-field in activities

### ISSUE THREAD

**Issue by bramvandartel** [Inter-Actief/amelie#553]
Currently, the only option on the website is to include a full description of an activity. For example for a weekly mailing, it doesn't make sense to send a complete activity description, since people most likely won't read that and people still have to go to the website to enroll, where again the same information is displayed. Therefore, it would be nice to have a TLDR-field for every activity that can be used in for example this weekly mailing.

**Comment by WKobes** [comment]
I do not think this is the way to go personally. If you would like to serve different content in the weekly mail, I would suggest making it possible to customize the text once activities are loaded into the mailing. TLDR field will be very confusing and might not be filled in correctly, causing only less informative weekly mails

**Comment by zwouter** [comment]
I believe that the description of an activity in the weekly mail should not be completely informative. If used correctly, the weekly mail draws a reader towards the activity page on the website, where all specific details and information about the activity can be found. 
With that in mind, I think a TLDR might be the wrong name for this, as a TLDR is normally very informative but not so exciting. Calling it a `promo' text or something of the like would be better in my opinion. This could then eventually also be used in other places.
I agree that if used incorrectly, it would be handy if the person who sends the weekly mails can edit this promo field to make it the way it's intended. Currently, when changing the description of an activity in the weekly mail, this also changes the actual description of the activity. With a special promo field, editing this to something which fits in the weekly mail actually could work.
