### ISSUE TITLE
Ending mandates gives a bad request (400) error

### ISSUE THREAD

**Issue by jellemaas** [Inter-Actief/amelie#554]
When a part of the mandates are selected on https://www.inter-actief.utwente.nl/personal_tab/authorization/terminate/ and you press the button end mandates it gives bad request (400) error.

**Comment by Kurocon** [comment]
```
Report at /personal_tab/authorization/terminate/
The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.
```

Too many inactive mandates have gotten built-up. I think it's best to clean them up manually via the command line for this one time. Can all of the current inactive mandates be terminated? Have all of them been removed from the physical administration? Have they all been checked?

**Comment by WKobes** [comment]
The last two seem to not be activated yet but only created today. Other option is that you do the ending in batches, so the error is not thrown

**Comment by Kurocon** [comment]
Cleanup via the page in smaller batches might work as well, can't hurt to try. The maximum per time is set to 1000, so keep it under that amount to be safe.

**Comment by jellemaas** [comment]
It is now at around 200, but the physical administration needs to be updated still. The others I have already deleted now

**Comment by WKobes** [comment]
If the administration is regularly kept up to date (say, every year), this bug should not occur. I do not think this is a bug worth addressing, so I am closing the issue.
