### ISSUE TITLE
Connection between Amelie and Alexia regarding active RFID cards is faulty

### ISSUE THREAD

**Issue by Jottee** [Inter-Actief/amelie#558]
Not sure whether this fits Amelie or Alexia better, but I assume Amelie needs to tell Alexia about active card changes.
Biggest issue: I can pay with cards via Alexia which have been disabled via my IA profile (took about a 5 min waiting period after the change).
Other inconsistencies: The cards stated within Alexia to be active are not the ones which are set as active via the Inter-Actief profile, example: I have 0 active cards in Amelie but 4 in alexia, then I activated a Student Card via Amelie and my Public Transit Card got added to the active card list in Alexia.

**Comment by Kurocon** [comment]
Cards in Alexia are shared across associations (card registered via IA also works at Abacus drinks), so we cannot disable them automatically in Alexia, as this might lead to 'loops' where IA disables a card, then Abacus re-registers it again.

**Comment by Jottee** [comment]
If cards are shared than that seems logical. I guess a feature request for Alexia to be able to disable cards solely for that system is too far-fetched, however the current situation seems skewed as well where deactivated cards can still be used for payments.

**Comment by WKobes** [comment]
I suggest closing this issue as a wontfix:

- if you really want a card blocked (i.e. lost/stolen), you would want to block this at all associations anyway
- supporting association-specific cards seems unnecessary and complicated
- if I block a card at Inter-Actief (deactivate), it gets deleted from alexia. Probably not all associations have implemented the API correctly, so it might be possible that old cards remain in the system. I suggest verifying that with all the associations.

All other solutions/improvements on this point seems to be more of an alexia issue.
