### ISSUE TITLE
Error if student pre-enrolls twice using the same student number

### ISSUE THREAD

**Issue by Quitlox** [Inter-Actief/amelie#562]
Very specifically, look at commit "8e07beae6635ff042443ae00e23eab7e2686b0cd" in file "members/forms.py" at line 555. 

In the FreshmenStudyDetails Step of the registration process (sign-up as member to Inter-Actief), the student number field check whether the student number already exists in the database to prevent a user from signing up twice. On a technical level, this field checks whether the student number field of the object type Person is unique. This field, however, does not check whether there exists an UnverifiedEnrollment object type with that student number (a pre-enrollment). 

A user is therefore able to pass the FreshmenStudyDetails step of the registration process with the same student number for a second time. The user will be able to reach the end of the registration process. On confirmation, the user will receive an internal server error as a the student number unique constraint on the UnverifiedEnrollment object type is violated.

**Comment by Kurocon** [comment]
Aaaah, _that_'s why we (supers) keep getting those "duplicate student number" error mails instead of it just being caught with the form validation. Thanks!
