### ISSUE TITLE
OAuth url results in an internal server error

### ISSUE THREAD

**Issue by bartleenheer** [Inter-Actief/amelie#567]
The following screenshot is taken after the link `/social_auth/token_login/TOKEN`, received in the OAuth email, is visited.

![WhatsApp Image 2021-09-19 at 10 26 14](https://user-images.githubusercontent.com/65281340/133920971-4d00702a-1d49-44f4-a1c8-0cb770df4721.jpeg)

**Comment by bramvandartel** [comment]
Only happens when you are not logged in.
