### ISSUE TITLE
Link committee booklet

### ISSUE THREAD

**Issue by bramvandartel** [Inter-Actief/amelie#575]
Change link on committees page to https://media.ia.utwente.nl/amelie/data/uploads/2021/10/04/Committee_Booklet_Bram_4.pdf

**Comment by WKobes** [comment]
Hi Bram, could you perhaps rename the file to `Committee_Booklet_21_22.pdf` and reupload? As the name is shown in the PDF, this is more professional. We might want to consider moving towards a static location of the file which can be replaced using FTP.
