### ISSUE TITLE
Remove email notification when a member accepts an activity invite

### ISSUE THREAD

**Issue by Quitlox** [Inter-Actief/amelie#576]
Whenever someone imports an ical of an Activity, and then proceeds to accept this invitation, an email job is dispatched to the committee informing the committee of the acceptation. This is not a very useful feature, and moreso, quite annoying.

**Comment by WKobes** [comment]
I think I have seen this behaviour before, and is only occurring in case a user is able to import the calendar with 'accept/deny' options. The email notification is as far as I know not sent by amelie, but the calendar provider, correct?

**Comment by Kurocon** [comment]
> I'm not completely sure, but I found the code in amelie/calendar/tasks.py suspicious.

That's for sending a callback to an external website for each enrollment
So you can enter a callback_url and amelie will send an HTTP call to that address for each new enrollment with the details of the person, along with the callback secret of that activity. I don't think we've really used it before, but it has nothing to do with the icals. That's just part of the behaviour of the calendar application, and cannot be influenced by Amelie
