### ISSUE TITLE
Rename default branch and check phrasing codebase

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#577]
As per intended BCP [Knodel & ten Oever](https://tools.ietf.org/id/draft-knodel-terminology-06.html) and changed [GitHub standards](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/), we should rename the default branch to `main`. 

Additionally, check if our codebase(s) unintentionally uses outdated phrasing.

**Comment by Kurocon** [comment]
Fixed with the open-sourcing and in https://github.com/Inter-Actief/amelie-private/pull/603
