### ISSUE TITLE
Tokens verlopen snel, en geen mogelijkheid nieuwe aan te vragen.

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#58]
Lieve WWW'ers,

Ik (namens de AppCie?) heb een klein probleempje met de API: Na verloop van tijd verloopt de LoginToken?, wat betekend dat de app niet meer naar behoren functioneert (ingelogde gebruikers kunnen meer activiteiten en foto's bekijken etc.) en de gebruiker in en uit moet loggen om het probleem te verhelpen. Een nieuwe token opvragen lijkt een goede, simpele oplossing, maar wij slaan de gebruikersnaam en het wachtwoord niet op de telefoon op (for obvious reasons), dus dit is niet mogelijk.

We moeten dus even kijken of we hier een elegante oplossing voor kunnen vinden (automatisch nieuwe token krijgen bij TokenExpiredError??), dan kan de AppCie? de nieuwe release de deur uit doen.

---

Een oplossing lijkt gevonden te zijn:
- Voor apps die gebruikersnaam en wachtwoord wel veilig opslaan kan een nieuwe token aangevraagd worden met deze data.
- Voor apps die met OAuth inloggen, die kunnen een refresh token gebruiken.

Kijken of dit ticket gesloten kan worden.

**Comment by SebastiaandenBoer** [comment]
Windows (Phone) heeft de methode voor het aanvragen van nieuwe tokens al geïmplementeerd en bij overgang naar OAuth zal gebruik worden gemaakt van refresh tokens.
