### ISSUE TITLE
Re-consider Kick-IT access to pre-enrollments

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#580]
Currently, the Kick-IT committee can access the pre-enrollment status, as well as print the pre-enrollment forms. 

While this technically is in compliance with the privacy policy (per https://privacy.ia.utwente.nl/#16-toegang-tot-gegevens ), this was originally only needed for one year where the Kick-IT was handling the enrollment forms.

This workflow might not be necessary any more, and maybe the enrollment status page, or only the form print pages, can be further restricted to be board-only. To discuss with WWW-supers and board about if this is wanted.

See also comments here: https://github.com/Inter-Actief/amelie-private/pull/521#issuecomment-946727091

**Comment by Quitlox** [comment]
To give this a bump, this is a simple fix and indeed seems unnecessary currently.

@bramvandartel Is this in your (board) opinion still necessary?
