### ISSUE TITLE
Foutive URL afbeelding 'CAPE groep'

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#59]
De API geeft de volgende URL voor de afbeelding van het bedrijf 'CAPE groep': ​https://media.ia.utwente.nl/amelie/

**Comment by SebastiaandenBoer** [comment]
Het schijnt een formatting issue te zijn:
`"image-url":"%s%s" % (settings.MEDIA_URL, str(company.app_logo)),` (/api/company.py > line 16).

Het is wellicht netter om een leeg veld (of `null`) terug te sturen in plaats van:
`"image-url": "https://media.ia.utwente.nl/amelie/"`
