### ISSUE TITLE
Search through old Activities

### ISSUE THREAD

**Issue by Quitlox** [Inter-Actief/amelie#591]
It would be nice to be able to search through the old activities. For example, to look at the description of an old activity.

https://www.inter-actief.utwente.nl/activities/old/

**Comment by WKobes** [comment]
Why is that page prefiltering for activities until *two days* before today? 🤔

**Comment by Kurocon** [comment]
> Why is that page prefiltering for activities until _two days_ before today? thinking

Took some time but I figured it out. It's the time that Amelie was last restarted or reloaded.

The initial values in the form (see link) used are set in the class and not in a constructor method, so they are only set once, when the application is either loaded, or when the class is first loaded.
https://github.com/Inter-Actief/amelie-private/blob/5bbc650c7cd711baa97570a0bf123d74743a919a/amelie/tools/forms.py#L35

To fix it we would simply need to overwrite the initial values in the init function.

**Comment by Kurocon** [comment]
Just for fun I traced this back to its origin, this is a pretty old bug!

https://github.com/Inter-Actief/amelie-private/commit/cc69739e503894540e9739ddabaef08854773f2b#diff-7e633da5e19172fde42d95b4c659e1e0adc420241cfad310295819e8e53904a1

Introduced in May 2012, where the .initial is started to be used for the filtering. Before that the old activity page filtering was always set hardcoded to the range 2009-06-30 to 2009-12-31 by default. Now the time of last reload _is_ better than that, but I think we can easily fix it up so it can be _even better_.
