### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#6]
Per django 1.5 is er initiele python 3 support, er wordt aangeraden nog niet over te gaan tot django 1.6, en we hebben nog wel python 2.7 installed staan, maar ten tijde van Amelié 2.1 moeten we misschien wel eens over zijn :)

**Comment by MMeent** [comment]
Notitie: we zitten momenteel op Django 1.8. Dit 

Dingen die gefixed MOETEN worden voor Python3, ivm syntaxerrors enzovoort:

- Dict.iteritems is vervangen door Dict.items
- print is een functie geworden
- `except Exception, e` is `except Exception as e` geworden
- importen binnen een functie is niet meer toegestaan
- '<>' is hernoemd naar '!='
- range heeft xrange vervangen in functionaliteit, xrange is weg
- \` literals zijn niet meer toegestaan
- tuple unpacking in een functiedefinitie is niet meer toegestaan

Depricated behaviour, onder andere:

- classes zijn nu altijd childclass van `object`, dit expliciet aangeven is in mijn opinie prettig
- unicode strings (`u""`) zijn niet meer supported. Het breekt niets, maar dirt in je codebase is niet netjes.
- metaclasses moeten nu via de class declaration aangegeven worden, niet meer als property.

Hier bijgevoegd twee gists voor commands die het project checken voor dingen die mogelijk veranderd moeten worden voor de migratie naar Python3:

[breaking](https://gist.github.com/MMeent/d3c7087724b023e70aad3f0324a1d94e)
[deprecated](https://gist.github.com/MMeent/f033ef0f6d988368d6ca20e93e58609f)

**Comment by J3173** [comment]
> importen binnen een functie is niet meer toegestaan

Volgens mij heeft dit alleen betrekking op star-imports (`from x import *`), dus imports van alle elementen binnen een module en niet op normale imports (`from x import y`). Deze normale imports binnen functies zijn nog steeds nodig om circulaire imports te voorkomen.

**Comment by Kurocon** [comment]
> classes zijn nu altijd childclass van `object`, dit expliciet aangeven is in mijn opinie prettig

Als je zo min mogelijk dirt in je codebase wilt hebben, en alle classes altijd toch al childclass zijn van `object`, zou ik het liever juist niet expliciet maken. Scheelt weer iets wat mensen gaan vergeten te doen, en zorgt voor (in mijn opinie) nettere code.

**Comment by MMeent** [comment]
goed punt, maar ik weet niet van hoe oude python we komen, en dus zou de behaviour van een stel classes kunnen veranderen. In 2.7 is het aangeven van inheritance vanaf object specifiek wel nodig om dezelfde behaviour te krijgen als die die in 3.0 gegeven wordt. 

Wat ik noemde was dan ook een hint naar het controleren van de huidige codebase op inheritance naar object dan dat het gewenst wordt voor 3.0. Dit is mogelijk verkeerd overgekomen.
