### ISSUE TITLE
streaming.ia video support in the Videos module

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#600]
It would be cool if we can add videos from our own streaming platform ( https://streaming.ia.utwente.nl ) to the website's video page. This way we can put the old Top 100 broadcasts, the Hamers Brewalong and some old lunch lectures (maybe privately) on the website so they can be found more easily. It would also allow us to add videos without needing to upload them to youtube.

**Comment by WKobes** [comment]
Cool idea!

Unrelated to this issue: I'm not sure whether the old top 100 broadcasts (mostly the 2019 edition) should still be (publicly) accessible at this point in time.

**Comment by Kurocon** [comment]
Well, that was easier than expected. PR soon!

![image](https://user-images.githubusercontent.com/1193988/145652958-9a0c9a82-8f80-4033-8fb0-0651907f0c74.png)
