### ISSUE TITLE
Numeric enrollment option

### ISSUE THREAD

**Issue by WJ44** [Inter-Actief/amelie#603]
For some activities, mostly merchandise and such, a numeric input for enrollment is required. This is now often achieved by having checkboxes for multiple amounts, usually 1, 2 and 4, so one can select any value from 0 to 7 or similar. It would be useful to have numeric input fields as enrollment option, where one can set a valid range.
Not the most important thing ever, but a nice quality of life thing that usually occurs multiple times per year.

**Comment by WKobes** [comment]
See also #517
