### ISSUE TITLE
Discharged editions of committees can no longer be mailed using their committee alias

### ISSUE THREAD

**Issue by nielsedegroot** [Inter-Actief/amelie#606]
If you are in the LuCie, you receive mail sent to lucie@ but also to your specific edition (e.g. 2021) through lustrum21@, for example. When the committee is discharged, you should no longer receive the email intended for lucie@, but you should continue to receive email specifically sent to your edition. This does not seem to work at this moment.

The LuCie may be a complicated issue because it is not an annually occuring committee, but an easier example: if I was part of Rially 2019 I should receive rially@ as long as that committee is active. After the committee is discharged (and _even when a Rially 2020 is charged_), I should still receive rially2019@, for example.

Preferred solution: make lustrum21@inter-actief.net, lustrum2021@inter-actief.net, lustrumpixelate@inter-actief.net, whatsoever still forward to the members of that edition's committee. Same for other committees who have multiple editions.

**Comment by Kurocon** [comment]
When a committee is 'discharged' (abolished), they are no longer 'working' for IA and their aliases are deactivated, as well as the active members accounts of people in the committee if they were only in that committee. This is how it has always worked.

If a period of time is wanted where the old committee is still reachable via their committee mail, they should not be abolished.

**Comment by WKobes** [comment]
For specific cases where this is necessary, an extra alias can be created. For regular cases, the committee should be abolished once the work of the committee is finished, and thus the alias by default will stop working.
