### ISSUE TITLE
Adding a checkbox to activity creation which automatically invited the MedIA

### ISSUE THREAD

**Issue by Michael-Janssen-dev** [Inter-Actief/amelie#609]
In the current workflow for committees, the WEEDFPS, the MedIA needs to be contacted actively by the organising committee. While the board has reiterated multiple times that this needs to be done, in practice, this is often forgotten/done too late. We think adding a checkbox "I want to have MedIA at my activity", where if this is active the MedIA automatically receives a mail with the request and activity details, would decrease the chance of this happening.

It would be a good idea to send the mail on behalf of the committee (committee@inter-actief.net), so that if the MedIA has any questions (which in practice does not happen often), they can reply to the incoming mail.

A separate checkmark for photo and video might also be desirable

**Comment by WKobes** [comment]
https://xkcd.com/1319/

**Comment by Quitlox** [comment]
Given:
- the fickleness of this particular workflow at IA
Who is to say that we will always have a MediaCie? What would happen if, _say,_ the cinema and flitcie were to merge?
- Wouter's fitting XKCD
- my own opinion that communication within the association is part of the committee experience and contributes to the feeling that we are actually an association ran by real people
- my own opinion that failing to communicate with other parties timely is a nice learning opportunity

I am going to close this issue.
