### ISSUE TITLE
Allow the board to enroll people past the maximum number of participants

### ISSUE THREAD

**Issue by WJ44** [Inter-Actief/amelie#612]
In exceptional cases, it can happen that the board wants to enroll someone for an activity when it is full, but enrollment/unenrollment is still open. Of course one can close enrollments, increase the maximum number of participants and then enroll them but is is a slight hassle. It would be nice if the maximum number of participants can be overruled when manually enrolling someone.
Not the most necessary feature, but a slight quality of life thing.

**Comment by bramvandartel** [comment]
Now that #12 has been implemented, this is already possible as the 'skip waiting list' option was added.
