### ISSUE TITLE
Total of dinner order at activity wrong total numbers

### ISSUE THREAD

**Issue by denisedh** [Inter-Actief/amelie#620]
At the bottom of an activity with dinner enrollment you see the totals of the different order options, with their prices, amount, and total price. The bottom row of this table, 'Eindtotaal' does not add up the above options correct. 

![issue](https://user-images.githubusercontent.com/35376037/162732659-0c965b7f-51c0-48fe-a25b-4d5238aa1744.png)

Thanks in advance!

**Comment by Kurocon** [comment]
Seems like it only counts one of each different product, probably an issue in the query. We will take a look!

**Comment by Kurocon** [comment]
Fixed in https://github.com/Inter-Actief/amelie-private/commit/8dc9eab29efe194e5710140396d2a24f2d2b0c33
