### ISSUE TITLE
Add event desk status: "Registered without EROs"

### ISSUE THREAD

**Issue by FrankvanMourik** [Inter-Actief/amelie#623]
The UT event desk would like us to already register an event even before the EROs are known, as this gives them a better overview of what events will take place at what days.

Therefore, it would be useful to add an extra status in the events tool for registered events without EROs. The automatic mail sent by the event desk has an extra paragraph when events are registered, but no EROs are added. This looks like this:

---------------------------
Dear NAME

You are receiving this e-mail because you registered the meeting 'ACTIVITY_NAME' on the date START_DATE_TIME till END_DATE_TIME at LOCATION with us.
To edit or supplement the meeting you registered, please visit the link below: 
LINK

Your meeting is large enough to require BHV personnel. Please provide the details on the BHV personnel you are assigning.

Sincerely,

The event management system.

---------------------------

**Comment by bramvandartel** [comment]
This issue will not be fixed, as upon registering ERO's no message is sent from the eventdesk. This means that even upon registering ERO's, the status on the website will not change from the initial state, except when the registration is accepted.
