### ISSUE TITLE
Leden statistieken

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#63]
Het is onmogelijk correcte statistieken te krijgen over het aantal leden binnen een bepaalde groep. Graag heb ik überhaupt een statistieken pagina waar bepaalde handige waarden op staan. Aantallen van: Eerstejaars jaarleden, Eerstejaars studielang, Hogerejaars jaarleden, Hogerejaars studielang, Medewerkers jaarleden, Andere verenigingsleden, Buitengewone leden, en inbitweenleden.

**Comment by Tijnoz** [comment]
Er is een /leden/statistieken waar die dingen mooi bij kunnen. Een linkje
naar die pagina is ook handig ;)

**Comment by Tijnoz** [comment]
Duplicate of #94
