### ISSUE TITLE
API calls localiseren niet

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#64]
Het lijkt erop alsof de API alles over talen negeert en nederlandse data returned. 

---

Artikel titels en content wordt gemixt (zonder logica) teruggegeven door de API. Daarnaast zijn een aantal zaken niet in het Engels beschikbaar zoals commissies e.d.

**Comment by SebastiaandenBoer** [comment]
Voor nieuwsartikelen geldt: de titels worden niet alleen in verschillende talen zonder logica teruggegeven, maar ook met verschillende opmaak (zie eerste titel).
![1](https://cloud.githubusercontent.com/assets/7795655/18528061/a5712058-7ac7-11e6-9687-e8bef0024044.png)
![2](https://cloud.githubusercontent.com/assets/7795655/18528060/a56c7544-7ac7-11e6-862f-8abb4718c205.png)
