### ISSUE TITLE
Do group family tree

### ISSUE THREAD

**Issue by supertom01** [Inter-Actief/amelie#642]
Since the website already keeps track of every dogroup and who is in which one. It would be perhaps interesting to maintain the do group family tree on the website. (Comparable on how it is now shown in at least the last version of IO Vivat). 

It could of course be more interesting to extend it later with more information, like who was in there, instead of just the groups themselves. But it depends a bit on how much personal information one would want to display on such a page.

**Comment by WKobes** [comment]
If showing names to all members/public: change in privacy regulations would be required
