### ISSUE TITLE
Push Notifications support voor Windows Phone

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#65]
Voor een WinRT-gebaseerde applicatie, zoals een Windows Phone 8.1 (WinRT), Windows 10 en Windows 10 Mobile, is het niet meer mogelijk om gebruik te maken van MPNS. In plaats hiervan wordt alleen de Windows Notification Service (WNS) gebruikt. Als er op dit moment gebruik wordt gemaakt van een Azure Notification Hub, dan is er geen verdere configuratie nodig, anders moet deze nog aangemaakt worden.

Voor implementatie van push notification in de nieuwe Windows app zijn de volgende values benodigd: -notification hub name
-servicebus namespace
-DefaultListenSharedAccessSignature?

**Comment by Sophietje** [comment]
Mogelijke bronnen om een Azure implementatie (en dus ook de limitatie van 500 gratis devices) te omzeilen, heb ik hieronder even opgesomd:

​http://www.jayway.com/2011/10/12/implementing-windows-8-push-notifications-an-example/ ​https://visualstudiomagazine.com/articles/2012/03/25/using-push-notifications-in-windows-8.aspx ​http://blogs.msdn.com/b/wsdevsol/archive/2012/10/04/walkthrough-creating-an-iis-server-to-use-with-wns-push-notifications-and-windows-store-apps.aspx

Het is dus mogelijk om buiten Azure om Push berichten te sturen naar Windows en Windows Phone devices die Windows (Phone) 8.0 of hoger draaien.

**Comment by Sophietje** [comment]
Ik heb besloten zelf de code maar te schrijven en daarvoor mezelf een beetje wegwijs te maken in Python. Bij deze de code die ik uit m'n mouw heb geschut aan de hand van de huidige wp_specific code, maar dan met WNS implementatie.

Alleen rest dan nu nog de vraag: "Hoe bepalen we welk type device een nieuwe registratie is?". Aangezien Windows Phone 8.1 zichzelf anders presenteert dan Windows 10 Mobile en Windows 10 Desktop. Kan iemand mij dit uitleggen en samen even kijken of daar dan nog wat voor gedaan moet worden?

from httplib import HTTPException
import logging
import json

from amelie.api.models import Device, Notification
from amelie.api.push import BaseService, register_push_service

from django.conf import settings

from textwrap import dedent


logger = logging.getLogger(__name__)

client_id = '';
client_secret = '';

def get_win_payload(notification, ontvanger):
    return dedent("""\
        <?xml version="1.0" encoding="utf-16"?>
        <toast>
        <visual>
        <binding template="ToastText02">
            <text id="1">Inter-Actief</text>
            <text id="2">{}</text>
        </binding>
        </visual>
        </toast>
    """).format(notification.parse_message(ontvanger))
    
def get_auth_token():
    payload = "grant_type=client_credentials&client_id=" + client_id + "&client_secret=" + client_secret + "&scope=notify.windows.com"
    
    self.hostname = 'https://login.live.com/accesstoken.srf'
    self.https_open()
    result = self.post_data(payload, 'application/x-www-form-urlencoded')
    self.https_close()
    
    data = json.loads(result)
    token = "Bearer {}".format(data["access_token"])
    return token

class WNSService(BaseService):
    """
    Represents a Windows Notification Service.    
    'client_id' and 'client_secret' are required.
    """
    
    headers = {"X-WNS-Type":"wns/toast", "Content-Type":"text/xml"}
    
    def push_notification_to_devices(self, notification, devices):
        """
        Sends the specific notification to the specified devices
        """
        if not isinstance(notification, Notification):
            raise TypeError('notification should be an instance of amelie.api.models.Notification')
        
        if Authorization not in self.headers:
            token = get_auth_token()
            headers['Authorization'] = token
        
        successful_devices = [];
        for device in devices:
            logger.debug(u"Sending push notification to {}".format(device))
            # noinspection PyBroadException
            try:
                payload = get_win_payload(notification, device.authorization.persoon)
                print payload
                self.hostname = device.push_token #todo is this actually safe??
                self.https_open()
                result, headers = self.post_data(payload, 'text/xml', self.headers)
                self.https_close()
                if headers['X-WNS-NOTIFICATIONSTATUS'] == 'received':
                    logger.debug(u"Sending push notification to {} succeeded".format(device))
                    successful_devices.append(device)
                else if "Token expired" in headers['WWW-Authenticate']:
                    token = get_auth_token()
                    headers['Authorization'] = token
                else:
                    logger.warning(u"Sending push notification to {} failed, removing push token".format(device))
                    device.push_token = None #clear the push token
                    device.save() #clear the push token
            except HTTPException:
                logger.exception(u"HTTP connection failed for device {}".format(device))
                pass
            except Exception:
                logger.exception(u"Sending push notification failed for device {}".format(device))

        return successful_devices


#register the windows notification server in the push server set.
register_push_service(Device.WP,WNSService)

**Comment by Sophietje** [comment]
Een ding waar ik absoluut geen fan van ben is xml builder spelen, daar hebben we libraries voor die valid xml produceren. Verder is requests een chillere library dan httplib.

Ik heb geen toegang tot mijn dev omgeving nu dus ik kan er weinig aan testen, is het goed als ik dat maandag (www-avond) even doe?

**Comment by Sophietje** [comment]
Geen probleem, zolang de inhoud van de xml maar gewoon hetzelfde is, dan werkt alles wat mij betreft. Over python libraries heb ik geen kennis, dus pas daar maar gewoon je eigen preferences toe.

Mijn doel was om jouw werk zo makkelijk mogelijk te maken, vandaar mijn 'best shot' naar python (waar ik verder niets mee doe).

**Comment by AVeenstra** [comment]
A initial implementation has been made and can be found on: [fix_ia_amelie#65](/Inter-Actief/amelie-private/tree/fix_ia_amelie%2365).

**Comment by AVeenstra** [comment]
Pullrequest is open
