### ISSUE TITLE
Add stock support to cookie corner [dirt road implementation]

### ISSUE THREAD

**Issue by LvanArkel** [Inter-Actief/amelie#656]
In the current system, the cookie corner does not keep track of how many products are currently available. The following improvement aims to improve this by including a stock count for each product which will be deducted by tallies, and the ability of the board to update this stock count whenever there is a new delivery.

This improvement is planned using the so-called "dirt-cobblestone-alphalt road implementation," where each step contains a functioning product with increasing requirements. The requirements are shown below as user stories. This issue will implement the dirt road implementation.

**Features dirt road implementation**
D.1 As a user, I want to see the (presumed) stock for each product when using the cookie corner terminal.
D.2 As a board member, I want to easily update  the stock of the cookie corner.
D.3 As a board member, I want to add stock based on the amount of boxes, which automatically calculates the correct increase in stock.
D.4 As a board member, I want to manually set the amount of items per box per product.

**Features cobblestone road implementation**
C.1 As a user, I want to see a difference between products which are sold out and those that are not.
C.2 As a user, I want to see an indicator if a product is almost sold out.
C.3 As a treasurer, I want an overview of the current stock for stock counts.

**Features asphalt road implementation**
A.1 As a user, I want to notify the board whenever the presumed stock of a product does not correspond to the actual stock
A.2 As a treasurer, I want to be able to import deliveries of products to update the stock count.
A.3 As a treasurer, I want stock counts to be easily importable into the bookkeeping software

**Comment by WJ44** [comment]
I would recommend against this, since it adds additional work for the treasurer without much benefit, and does not really align with the way the finances are handled. Should the whish still exist to keep stock, I would highly recommend having Exact Online as the single source of thruth for this, as it has stock count implemented and even has an app to easily count and update stock. The website could then access this through Ecact's API.

**Comment by WJ44** [comment]
Furthermore, D.1., C.1. and C.2. can be accomplished symply by turning around, without this requiring extra effort from the board, or causing beration as described in A.1.

**Comment by supertom01** [comment]
No longer relevant
