### ISSUE TITLE
Update to Celery 5 and Flower 1.2

### ISSUE THREAD

**Issue by Kurocon** [Inter-Actief/amelie#657]
After https://github.com/Inter-Actief/amelie-private/pull/504 is merged, we should upgrade to the newer celery and flower, as flower finally added support for celery 5+.

**Comment by WKobes** [comment]
@Kurocon I see this is in the open-source milestone. Should this be fixed still?

**Comment by Kurocon** [comment]
Not blocking imo, we can do this along with Django 4.2 migration or with a separate dependency update after open sourcing.
