### ISSUE TITLE
Leden mailsysteem tweetalige mails laten versturen

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#66]
Op ​https://www.inter-actief.utwente.nl/leden/mailing/ kan bestuur een mailing versturen naar leden, echter is er hier geen mogelijkheid tot het vertalen van deze mails. Het zou met het oog op internationalisatie natuurlijk mooi zijn als dit systeem net als de weekmail automagisch engelse mails kan versturen :).

**Comment by Sophietje** [comment]
Denk ook aan de automatische mails zoals incasso mailingen

**Comment by Sophietje** [comment]
Het mooist zou zijn om dit te doen aan de hand van de taalvoorkeur in het profiel

**Comment by J3173** [comment]
Alle automatische mails zijn inmiddels tweetalig en worden verstuurd op basis van de taalvoorkeur van het lid. Het gaat dus alleen om de handmatige mails.
