### ISSUE TITLE
Refactor archaic language to modern language

### ISSUE THREAD

**Issue by WKobes** [Inter-Actief/amelie#668]
See https://datatracker.ietf.org/doc/draft-knodel-terminology/10/

- [ ] Rename branch master to main
- [ ] Check codebase for whitelist -> allowlist, blacklist -> blocklist
- [ ] Check codebase for any references to master/slave -> primary/secondary

**Comment by Kurocon** [comment]
Working on this at the moment; What about the `Person.webmaster` property?
In my opinion it is an accepted term, with no real accepted alternative. What do you think?
Maybe it could even be removed, I don't really think its used for anything important at the moment (that we could not solve with a regular Claudia group)

**Comment by WKobes** [comment]
> Working on this at the moment; What about the `Person.webmaster` property? In my opinion it is an accepted term, with no real accepted alternative. What do you think? Maybe it could even be removed, I don't really think its used for anything important at the moment (that we could not solve with a regular Claudia group)

The web indeed seems to provide no real alternative. I'll add a separate issue to remove the property entirely, since it is and probably will not be used. Then we can close this issues upon merge

**Comment by WikiRik** [comment]
What would be wrong with `(site )admin(istrator)` instead of `webmaster`?

**Comment by WKobes** [comment]
Nothing but the propery did not indicate admins of the main website, but only provided certain access to folders of sub-sites like symposia etc. So using admin would be confusing also. Since we don't use the property any more, we'll just remove it
