### ISSUE TITLE
Filtering activities by label

### ISSUE THREAD

**Issue by maarten0912** [Inter-Actief/amelie#671]
On the page https://www.inter-actief.utwente.nl/activities/:

It would be useful to have the options click on a specific label, which would show only the upcoming activities in that specific category. With this filtered list there should just be an added button to reset the filter.

**Comment by bramvandartel** [comment]
While being at it, some questions/thoughts/ideas:

- Would it be nice to have these categories be distinguishable in the weekly mail in some way?
- Maybe let people select in their profile the type of activities they are interested in and do something with it? Such as recommended activity. (Note: do really think about whether this is desirable)
- Do something with the labels in Discord posts or in metadata when sending a link?

**Comment by SimplyPancake** [comment]
Following done:
- Added week mail tags of the activity label
- Added activity label to the opengraph short description
- Added filter page per activity label type (by clicking on the label)

**Comment by supertom01** [comment]
@SimplyPancake I see that you moved this ticket to await acceptance. Could you please also create a PR? Thanks!
