### ISSUE TITLE
Do not display `Label` of activity if it's `Unknown`

### ISSUE THREAD

**Issue by WikiRik** [Inter-Actief/amelie#675]
For example; https://www.inter-actief.utwente.nl/activities/6933/
The label (or type in Dutch) could be made invisible if it's not provided.

If this is not wanted, it would be a good improvement to not display `Unknown` in Dutch, but `Onbekend` or something similar.

**Comment by Kurocon** [comment]
The unknown is only shown for activities that were added before the labels were introduced, and cannot be chosen for new activities. Someone forgot to add a Dutch translation for it, I just added it.
