### ISSUE TITLE
Company activities do not support the new activity labels

### ISSUE THREAD

**Issue by Nierot** [Inter-Actief/amelie#678]
![Screenshot_20221110-081253__01](https://user-images.githubusercontent.com/56843328/201024667-381097dd-4af4-4bf9-a332-79072bc35ca3.jpg)
![Screenshot_20221110-081308](https://user-images.githubusercontent.com/56843328/201024672-6ea6d8ea-9813-4ef4-aa5c-8ce412acf6a1.jpg)

**Comment by WKobes** [comment]
Is it the same for educational events?

**Comment by Kurocon** [comment]
Labels were implemented on the Activity object, not on the base Event object, so yes

**Comment by WKobes** [comment]
So we can just default these categories to Career and Education labels respectively right?

**Comment by Kurocon** [comment]
That would seem logical yes
