### ISSUE TITLE
Foto's worden verkeerd gesorteerd

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#7]
Bij /activiteiten/fotos/upload wordt de lijst met foto's verkeerd gesorteerd. Blijkbaar heeft os.walk() lak aan volgorde.

Fixplz? Dank u!

Cas

**Comment by Kurocon** [comment]
Een simpele sort over de lijst zou het moeten fixen

**Comment by Kurocon** [comment]
Fixed by @AVeenstra in https://github.com/Inter-Actief/amelie-private/commit/f5e2badc2f060e8fbf7f37a7f1a60a0b40719434
