### ISSUE TITLE
getActivityStream vangt ongeldige input niet goed af

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#70]
De API-functie getActivityStream vangt ongeldige input (fout datumformat) niet goed af. 
Exception:
    ValueError: time data '18/09/2015' does not match format '%Y-%m-%dT%H:%M:%S'

Request:
    {"id":"id", "method":"getActivityStream", "params":["18/09/2015", "18/10/2015","token"]}

Stacktrace (most recent call last):
    File "jsonrpc/site.py", line 164, in response_dict
    R = apply_version[version](method, request, D['params'])
  File "jsonrpc/site.py", line 129, in <lambda>
    '1.0': lambda f, r, p: f(r, *p)}
  File "amelie/api/activitystream.py", line 32, in get_activity_stream
    beginDate = datetime.strptime(beginDateString, "%Y-%m-%dT%H:%M:%S")
  File "python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))

Sentry: ​https://sentry.ia.utwente.nl/www/amelie/group/301/

**Comment by J3173** [comment]
Dit is een tijdje geleden gefikst.
