### ISSUE TITLE
Cookie Corner Wrapped

### ISSUE THREAD

**Issue by Nierot** [Inter-Actief/amelie#705]
It would be very fun if we could have a "Cookie Corner Wrapped" for 2022 (similar to Spotify Wrapped). It shows a user what their statistics are for the cookie corner in 2022. Think of how many calories one consumed or what % of sales they contributed to for certain products.

**Comment by Nierot** [comment]
https://abacus.utwente.nl/en/account/cookie.html

**Comment by Mihai98924** [comment]
Fixed in #708
