### ISSUE TITLE
OAuth: finalize_remote login does not correctly catch exceptions

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#71]
Exception: 
    Internal Server Error: /oauth2/process_auth_code/1/

Root cause: MultiValueDictKeyError: "'code'"

Request: 
    URL: https://www.inter-actief.utwente.nl/oauth2/process_auth_code/1/
Method: GET
Query: error=access_denied

Stacktrace (most recent call):
     File "django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "amelie/oauth2/views.py", line 119, in finalize_remote_login
    data = consumer.get_token(request.GET['code'])
  File "django/utils/datastructures.py", line 319, in **getitem**
    raise MultiValueDictKeyError(repr(key))

Sentry: https://sentry.ia.utwente.nl/www/amelie/group/192/events/4944/

**Comment by Kurocon** [comment]
Onbekend of dit nog steeds een probleem is.

**Comment by SebastiaandenBoer** [comment]
Still seems to be a problem.

**Comment by WKobes** [comment]
@Kurocon is this still relevant?

**Comment by Kurocon** [comment]
Outdated, this is the old oauth module that was removed quite some time ago
