### ISSUE TITLE
Photos are shuffled in album after upload

### ISSUE THREAD

**Issue by jeffreybakker** [Inter-Actief/amelie#719]
Previously (I assume before the update), pictures in the album were sorted by filename. When uploading the Top 100 pictures, I noticed that the pictures were randomly shuffeled after adding them to the album.

**Expected behaviour**
Photo's in an album are displayed in alphabetical order of filename.

This, however, might still leave some edge cases, therefore, I suggest an alternative sorting method where photos in an album are primarily sorted on date taken (in EXIF data if the photographer does not hide them on export), and secondarily on filename.

**Comment by Kurocon** [comment]
This is probably because in the new uploader photos are renamed to a UUID after uploading to avoid too long filenames, invalid characters, etc.

**Comment by supertom01** [comment]
Closed by #840
