### ISSUE TITLE
Externe activiteiten in weekmail

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#72]
Zou het mogelijk zijn om externe activiteiten in de weekmail te kunnen zetten. Zo zouden we ook activiteiten van ENIAC kunnen toevoegen aan de weekmail.

**Comment by J3173** [comment]
Aangezien we waarschijnlijk ook onderwijsactiviteiten (zie #87) in de weekmail willen hebben, misschien het systeem zo aanpassen dat alle Events (de algemene superclass) in weekmails kunnen.
