### ISSUE TITLE
App-inschrijvingen bij activiteiten

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#73]
Op het moment wordt er een i-tje getoond wanneer er iets speciaals is met een inschrijving bij een activiteit, zou het mogelijk zijn om een apart icoontje te laten zien voor app inschrijvingen, zodat dat meteen duidelijk is dat het om een app inschrijving gaat.

**Comment by Tijnoz** [comment]
We hebben het even overlegd en dit leek ons niet bijzonder nuttig voor de hoeveelheid aanpassingen.
