### ISSUE TITLE
API "searchGallery" issue

### ISSUE THREAD

**Issue by maarten0912** [Inter-Actief/amelie#757]
The API does not respond correctly when searching for photos. For example, a request with 

```{"jsonrpc":"2.0","id":319355730,"method":"searchGallery","params":["aXi"]}```

(when using the website) will get the response

```Unable to handle your request. Please ensure you called the right entry point. If not, this could be a server error.```

In this case, this results in the photo search function not working. This error might also occur at other API entry points.

**Comment by Kurocon** [comment]
Duplicate of https://github.com/Inter-Actief/amelie/issues/750
