### ISSUE TITLE
Login link in activity pages broken

### ISSUE THREAD

**Issue by kasteelharry** [Inter-Actief/amelie#759]
The link on the activities pages where one can log in before enrolling for an activity is broken. When clicking the link nothing happens

**Comment by Kurocon** [comment]
Already fixed in https://github.com/Inter-Actief/amelie/pull/758

( https://github.com/Inter-Actief/amelie/pull/758/files#diff-f663f194acc1ced38f93f46a0a6b358854d40ba581fc2c593fa021644a47a3dfR137 )

**Comment by elisaado** [comment]
Has this been merged yet? The links are still broken.

**Comment by Kurocon** [comment]
The PR https://github.com/Inter-Actief/amelie/pull/758 is still open, so not yet.
