### ISSUE TITLE
Make youtube upload button more obscure

### ISSUE THREAD

**Issue by Oliver-WD** [Inter-Actief/amelie#763]
At https://www.inter-actief.utwente.nl/videos/ you can see al IA's video's, and MedIA members can upload new video's when logged in using the upload buttons on the top left of the page. There are two buttons: streaming.ia and youtube. The youtube account is no longer used, so this button can be removed.

**Comment by Kurocon** [comment]
But the latest video uploaded is a youtube video (RIAlly aftermovie)?

On a more serious note, I think it's fine to leave the feature in. Even if the MedIA isn't using it, it might be nice to be able to add a youtube video (not necessarily from our own channel) to the site in the future. We could look at making the button a bit more obscure or making the Streaming button more pronounced instead.

**Comment by KasteelMila** [comment]
It is correct that the latest video is RIAlly aftermovie but that was before I know we would want to do everything with streaming.ia. Not deleting the button is fine but make as you said a bit more obscure :)
