### ISSUE TITLE
Facial Recognition in photo albums

### ISSUE THREAD

**Issue by Migushthe2nd** [Inter-Actief/amelie#765]
A cool idea for (probably) the new backend would be the ability to filter photos by your own face. For example, there could be a section on the account page that shows a link to view all photos you're in.

A library that could be used is [ageitgey/face_recognition](https://github.com/ageitgey/face_recognition). You'd ofc. get the best performance with a GPU that supports CUDA, but should be doable on a CPU due to the limited number of images and interval at which new photos are uploaded.

It doesn't seem too advanced, and probably consists of two parts:
1. User must have a profile picture set in their IA account
    1. User uploads image
    2. Detect face
    3. Store face data (e.g. in a db table, https://github.com/ageitgey/face_recognition/issues/43)
2. Albums should get analyzed before being shown on the website
    1. New photos get uploaded
    2. The faces in a photo are matched against the db
    3. We store the ids of the users in the picture in the Amelie db (don't know its structure)

There is the situation where someone uploads profile picture that is not them. We'll have to discuss how this should be handled. (enabling this features requires verification by a board member?)

This facial recognition stuff should probably be run outside of the Amelie backend service as a microservice or smth. This external service could independently store facial data in its own db for complete isolation. Another way would be to simply match the folder with all IA profile pictures against the newly uploaded album, but you'd be re-analysing profile pictures every time (which gets more expensive with every new user). We'll have to see what the reliability of this recognition is on the photos uploaded.

Will affect our Privacy Statement.

**Comment by Migushthe2nd** [comment]
I'm not part of the WWW committee, but I'd be willing to implement this even in the current Amelie version.

**Comment by Migushthe2nd** [comment]
@pietervanheijningen

**Comment by Kurocon** [comment]
This is not going to be implemented, because we are not allowed to process the pictures in that way according to our privacy policy.
