### ISSUE TITLE
Link committee logo with committee mail

### ISSUE THREAD

**Issue by KasteelMila** [Inter-Actief/amelie#774]
Add the committee logo to the committee mail

**Comment by Kurocon** [comment]
Hi Mila, what do you mean by this issue? That the committee logo should be added to the signature of mails sent from the committee e-mail in GMail?

**Comment by KasteelMila** [comment]
No not the signature, the profile picture (see below) as it also displayed on the wiki 

![Screenshot 2023-09-18 at 12 41 48](https://github.com/Inter-Actief/amelie/assets/113614759/9e3b2bbb-b598-4ac2-90e1-4b5357f12911)

**Comment by Kurocon** [comment]
Aah, I see, thanks for the clarification. This is the group picture in GSuite. This should be possible pretty easily I think

**Comment by Kurocon** [comment]
I took a small look at it, and unfortunately Google does not support avatars for groups. So this is not possible after all.
