### ISSUE TITLE
EC rights educational pages

### ISSUE THREAD

**Issue by maasrf** [Inter-Actief/amelie#775]
As a member of the education committee you can currently change the educational information page (as the board would). It also looks like you can change the pages of for example the educational bouquet and IDEA pages. Only when you click on the edit button it tells you you do not have the authority to go to that page. I would recommend giving authority if possible and otherwise at least removing the edit button when the person does not actually have edit rights

**Comment by bramvandartel** [comment]
It seems that a part of the educational pages is actually an /about page. Depending on preference, the edit button can be removed from templates or a Page can get an 'educational' tag/checkbox that allows the EC to edit them.
