### ISSUE TITLE
I/O Vivat digitaal beschikbaar maken

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#78]
Hoi,

Zouden jullie kunnen kijken naar een optie om de i/o vivat digitaal beschikbaar te maken? Het lijkt ons leuk om er doorheen te kunnen bladeren met een pdf reader zodat iedereen de i/o vivat online kan bekijken en lezen.

Alvast bedankt.

**Comment by Sophietje** [comment]
@11gamer11 How far are you with this ticket? Kimberly came to me today because she would like to see this implemented somewhere in the near future and she had an idea what you could use to implement this

**Comment by kimberlyh** [comment]
I was looking then at https://issuu.com/, at their free plan. But it seems to have changed a bit, so I do not know now for sure if this could be something we can use.

**Comment by niomaster** [comment]
So, to revive this ticket: what are the requirements here? Is there anything wrong with just using a generic pdf reader?
