### ISSUE TITLE
Aanpassingen weekmail applicatie

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#8]
Weekmail wordt in Amélie ingebouwd (Lennart?)

Features als aanvulling op huidige weekmail: 
-Automatisch HTML en plaintext 
-Plaintext {{ontvanger.voornaam}} aanpassen 
-Nieuws variabel aantal
-Facebook event werken (select stukje onder event)

**Comment by J3173** [comment]
@windwarrior Dit is toch zo goed als af, op de losse tickets na?

**Comment by Sophietje** [comment]
Lennart: "Has all been fixed"
