### ISSUE TITLE
Icoontjes van activiteiten toevoegen aan de API

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#82]
Activiteiten hebben tegenwoordig een icoon dat weergegeven wordt in de zijbalk. Dit icoon kan gebruikt worden om een eerste indruk van de activiteit te geven. Als dit in de API verwerkt wordt, kunnen ook in de app deze icoontjes gebruikt worden.

Kusje kusje knuffel, Waals

**Comment by SebastiaandenBoer** [comment]
Om dit te doen moet line 46 in activitystream.py worden veranderd van:
`"image-url": "https://www.inter-actief.utwente.nl/appcie.png",`

naar:
`"image-url": activity.afbeelding_icoon if activity.afbeelding_icoon else None,`
