### ISSUE TITLE
Random foto niet zichtbaar bij afgelopen activiteiten

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#83]
Als er bij een activiteit foto's zijn gemaakt, en je later de pagina van deze activiteit bezoekt, dan staat hier een mooi blok aan de rechterkant met "Er zijn foto's gemaakt bij deze activiteit, bekijk alle foto's" Hieronder hoort een random foto te staan uit het album dat bij deze activiteit hoort. Hier wordt netjes een div voor gemaakt echter staat er helemaal geen random foto in deze div...

Kusjes, Sophie

**Comment by J3173** [comment]
Misschien gerelateerd aan #99?
