### ISSUE TITLE
Add overview of extra options in indication of signup

### ISSUE THREAD

**Issue by P1mguin** [Inter-Actief/amelie#837]
When going to the overview page of the activity, the website currently indicates whether you are signed up for the activity:
![image](https://github.com/Inter-Actief/amelie/assets/57039167/916769f2-8ec5-4bd4-bdf7-4469dd755b46)

It would be well appreciated if this indication also indicated the extra options you signed up for. If this is already the case, an indication should provided for which options you have not signed up.
![image](https://github.com/Inter-Actief/amelie/assets/57039167/c53bf8db-b9ec-4146-b904-1e513252aac6)

**Comment by Kurocon** [comment]
We already add such an overview to the enrollment mail (see image), so this should not be too difficult to also add on the activity page.
![image](https://github.com/Inter-Actief/amelie/assets/1193988/e3dd816a-89d5-40b6-a7cf-5b2b581cb55a)
