### ISSUE TITLE
Add a date format hint

### ISSUE THREAD

**Issue by supertom01** [Inter-Actief/amelie#841]
For all the date fields on the website, if someone enters a date by hand, they have to essentially guess the format. It would be nice to add the expected formatting (YYYY-MM-DD).

**Comment by Berehum** [comment]
We still use input type text! Since input type date is now widely supported we might want to move to that. That would also fix this issue.

**Comment by Berehum** [comment]
DateTimeSelector already has a bootstrap picker, so for now we will continue using that. For DateSelector, we will start using the HTML type.
