### ISSUE TITLE
Active members mailing built in the site

### ISSUE THREAD

**Issue by Mathijs-Vogelezang** [Inter-Actief/amelie#845]
We can easily write and format weekmails, education mails and master mails through [https://www.inter-actief.utwente.nl/weekmail/](https://www.inter-actief.utwente.nl/weekmail/), which are nicely formatted, however the html for active members mailings needs to be handmade and looks different for every mail provider. Can a function be made for active members mailings which works similar to the weekmail?

**Comment by Kurocon** [comment]
We can add a new type to the weekmail application, similar to how we already have the mastermail and education mail in there, would that solve the problem for you @Mathijs-Vogelezang ?
