### ISSUE TITLE
Er zijn geen onderwijsactiviteiten

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#87]
Het zou mooi zijn als de OC apart activiteiten kan toevoegen, net als de externe activiteiten. Deze kunnen misschien het beste tussen de gewone activiteiten, met een markering om ze te onderscheiden van de gewone activiteiten (kleur? badge naast de titel? bolletje links van de activiteit zoals op de poster?)

**Comment by J3173** [comment]
Het model en het aanmaken van activiteiten is al gedaan door @niomaster. Deze staan nog niet op de frontpage of op andere plekken (app, weekmail).
