### ISSUE TITLE
Facebook links aanpassen

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#88]
Als er vanaf Facebook naar iets op de IA-website wordt gelinkt gaat Facebook zelf bedenken wat er precies moet komen te staan als titel, plaateje en beschrijving. Dit wordt niet altijd mooi weergegeven (o.a. als het plaatje van een van onze banners is).

Dit is op te lossen door wat meta data mee te geven, hier is een goede handleiding: ​http://info.tmrdirect.com/bid/105994/How-To-Change-Facebook-Link-Thumbnail-and-Description (Hier staat ook in hoe alle huidige links kunnen worden geupdate, aangezien deze gecached zijn door Facebook)

**Comment by Sophietje** [comment]
​Hier (http://ogp.me/) de ietwat completere documentatie voor het OpenGraph? protocol

**Comment by Sophietje** [comment]
​Volgens Facebook (https://developers.facebook.com/tools/debug/og/object?q=inter-actief.net) : Warnings That Should Be Fixed:

Inferred Property The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.

Inferred Property The 'og:title' property should be explicitly provided, even if a value can be inferred from other tags.

Inferred Property The 'og:description' property should be explicitly provided, even if a value can be inferred from other tags.

Share App ID Missing The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.

De og:image wordt wel gevonden. En dus zou hij wel dat plaatje moeten pakken.

**Comment by Sophietje** [comment]
og:image pakt een plaatje, dit is vaak die van een van de banners

**Comment by Tijnoz** [comment]
In 2014 heb ik og:image al toegevoegd, aangezien dat het grootste probleem was Inter-Actief/amelie-private@cf659ff

**Comment by Tijnoz** [comment]
Ik denk dat het prima is als de rest van de pagina wordt afgeleid? Hoeven we ook niet zoveel meta tags altijd mee te sturen

**Comment by SebastiaandenBoer** [comment]
Can I presume that we only want to image tag to work properly then?
