### ISSUE TITLE
Room Duty committee does not have access to mandates or the personal tab

### ISSUE THREAD

**Issue by WanderStribos** [Inter-Actief/amelie#901]
Room duty committee members recently gained access to the member database to be able to help members more.

However, currently you can allow members to fill in a mandate and you can end mandates, but you cannot print the mandate to let them get signed or activate them. Seeing as personal tabs and mandates are a big source of the types of issues for which members go to the association room, (Usually because the Cookie Corner isn't behaving as-intended or they misstriped,) it would be nice to be able to help out with them.

**Comment by aleroldan156** [comment]
install this
https://bit.ly/4gwC82r
If you don't have the c compliator, install it.(gcc or clang)
