### ISSUE TITLE
Statistieken pagina voor bestuur

### ISSUE THREAD

**Issue by Sophietje** [Inter-Actief/amelie#94]
De volgende hoofdstatistieken toevoegen:
Totaal aantal leden 885 
Aantal actieve leden (INF/BIT/Anders) 126 (104/22/0) 
Aantal actieve eerstejaars (INF/BIT) 23 (21/2) 
Aantal primaire eerstejaars (INF/BIT) 97 (64/33) 
Percentage actieve leden 14,24% 
Percentage actieve primaire eerstejaars 23,71% 
Aantal commissies 33 
Gevulde commissieplekken 208 
Gemiddeld aantal commissies per actief lid 1,65
aantal mensen met 1 commissie
aantal mensen met 2 commissies
aantal mensen met 3 commissies
enzo....
aantal internationale mensen
aantal actieve internationale mensen...

**Comment by Sophietje** [comment]
Eerstejaars ophalen lijkt lastig, hoe wil je dit doen? Kijkende naar begin inschrijving/studiejaar kan incorrecte gegevens geven

**Comment by Tijnoz** [comment]
Zonder nog te kijken naar welke data we hebben, moet eerst de vraag worden
beantwoord: Wat is een sjaars?
- Als je na je eerste jaar opnieuw begint?
- Als je switcht van studie?
Etc.

**Comment by Sophietje** [comment]
Deze statistieken zijn nu allemaal te vinden op /leden/statistieken op de statistieken na betreffende eerstejaars
