### ISSUE TITLE
Bestuur dashboard maken

### ISSUE THREAD

**Issue by 11gamer11** [Inter-Actief/amelie#97]
Een aparte pagina met overchten en handige links maken (overzicht of alles voor activiteiten is geregeld)

**Comment by Sophietje** [comment]
We can make a new page with useful links for the board, however at this point we will not implement some kind of overview for activities. If there are any specific features that the board wants, we can/will consider them.

**Comment by Kurocon** [comment]
Closed because there is no concrete plan for such a dashboard.
