### ISSUE TITLE
Fotoboek pagina crash

### ISSUE THREAD

**Issue by MMeent** [Inter-Actief/amelie#98]
De fotoboek-pagina (/activiteiten/fotos/) crashed op het moment dat het fotobestand niet aanwezig is in de map. 

Dit kan opgevangen worden door niet de eigenchappen van de foto direct te gebruiken, maar deze via properties o.i.d. op te vragen, en bij een missend bestand een default-waarde door te geven, in plaats van een error te gooien.

**Comment by SebastiaandenBoer** [comment]
This was fixed in Inter-Actief/amelie-private#245
