### ISSUE TITLE
Foto's bij commissie

### ISSUE THREAD

**Issue by niomaster** [Inter-Actief/amelie#99]
Bij elke commissie staat een blokje voor foto's van afgelopen acitiviteiten. Klopt het dat die leeg is zoals [hier](https://github.com/Inter-Actief/amelie-private/blob/master/amelie/leden/templates/commissie.html#L85)?

**Comment by J3173** [comment]
Daar zou volgens mij wel wat moeten staan. Misschien gerelateerd aan #83?
